### ISSUE TITLE
Первая загрузка главной с косяком

### ISSUE THREAD

**Issue by vfedyanov** [vfedyanov/rosobmen#1]
http://shot.qip.ru/00etiM-6UvvpmcCs/

**Comment by Igorbek** [comment]
Это проблема верстки. Возвращаю тебе @vfedyanov

**Comment by StepanOvchinnikov** [comment]
Если вы про удвоенную шапку, то в верстке я такой проблемы не наблюдаю
http://shot.qip.ru/00dQu8-519gZJGVwR/

**Comment by Igorbek** [comment]
Верстка как есть, так и вставлена.
Проблема в том, что скрипт выполняется до загрузки картинки и что-то делает.
В результате, когда работает с хостинга, а не локально (соответственно время загрузки картинки значительно больше), картинка исчезает и появляется двойное меню.

**Comment by shkarupa-alex** [comment]
Коллеги, вы можете мне показать на живом примере данный баг?
При этом я подразумеваю что верстка в отдаваемой вашим сервером странице должна полностью совпадать с исходной.

Не совсем понимаю смысла слова "локально" в описании проблемы. Вот тут http://test.ivserv1.tmweb.ru/rosobmen/ проблему наблюдаете?

**Comment by StepanOvchinnikov** [comment]
проблема наблюдается при первом открытии страницы 
http://plazma.azurewebsites.net/

при втором -- нет ее

у Игоря значительно более медленный хост, вероятно, чем tw

**Comment by shkarupa-alex** [comment]
Дело в том что у меня что при первом что при втором открытии указанной ссылки в принципе не отображается картинка с указанного хоста
https://www.evernote.com/shard/s303/sh/1d8aad5a-b445-401b-8045-4518659d1bca/d26b0056e212c840aabde9ef3950d0bd

**Comment by Igorbek** [comment]
Парни,
в случае правильной работы, на `div.index-block` ставится `height`.
в случае данной ошибки, он не установлен и высота считается нулевой.
с версткой вы давали скрипты. они подключены. там в коде есть:

``` js
if( $('.index-block').length > 0){
        heightIndexBlock();
        $(window).resize(heightIndexBlock);
    }
function heightIndexBlock(){
    var height = $(window).height() - $('.navbar-main').height();
    $('.index-block').height(height);
}
```

очевидно он отрабатывает неправильно, раз высота не устанавливается.

**Comment by Igorbek** [comment]
Парни, моя вина. Причину нашел, оказалось, что jquery.placeholder AMD не поддерживает и иногда не успевает подгружаться, что вызывает ошибку, и до исполнения того кода не доходит.
will be fixed. прошу прощения за срач.
