### ISSUE TITLE
Кнопки Управление и Профиль 

### ISSUE THREAD

**Issue by olga7** [vfedyanov/rosobmen#100]
зачем рядом две кнопки-ссылки, ведущие в одно и то же место  "Управление" и "Профиль-Личный кабинет"? http://shot.qip.ru/00mxnL-59mYYBh5p/
Если их по дизайну должно быть две, то вторая по-любому должна быть "Добавить свое предложение" (или как-то так)

**Comment by Igorbek** [comment]
В дизайне ничего не было, пришлось додумывать. Пишите как сделать.

**Comment by vfedyanov** [comment]
Перенесено в доп тз
