### ISSUE TITLE
картинка обрезана

### ISSUE THREAD

**Issue by olga7** [vfedyanov/rosobmen#102]
http://shot.qip.ru/00mxnL-59mYYBh5t/

**Comment by Igorbek** [comment]
Я размеры не выставлял. Это все карусель.
Надо б, чтоб верстальщик посмотрел. @StepanOvchinnikov

**Comment by shkarupa-alex** [comment]
Нужно заменить вызов слайдера для этого элемента вот на этот 
$('.product-slider-inner').carouFredSel({ 
            responsive: false,
            auto: false, 
            scroll:{
                fx: "crossfade"
            }
        });

И в стилях есть изменения https://www.dropbox.com/s/utxsh3v6oux7bej/product-slider.zip?dl=0
эту папку в нашей верстке замените на приложенную и скомпилируйте

**Comment by Igorbek** [comment]
Дайте, плз, уже скомпилированную верстку.

**Comment by StepanOvchinnikov** [comment]
Озадачил Алексея

**Comment by shkarupa-alex** [comment]
Верстальщика сейчас нет, поэтому собрать верстку воедино (с той структурой которая была изначально) не могу.

Вот как это выглядит на бою http://test.ivserv1.tmweb.ru/rosobmen/product.html
Изменения в 2х файлах:
1. main.js
2. less/product-slider/block.less

https://www.dropbox.com/s/jvlw9ys6o5glbs4/rosobmen.zip?dl=0
Приложить кроме как через дропбокс не могу - аттачатся только картинки

**Comment by Igorbek** [comment]
откатил (Igorbek/plazma#161), жду #177
