### ISSUE TITLE
назад с детальной карточки

### ISSUE THREAD

**Issue by olga7** [vfedyanov/rosobmen#106]
после того как я разобралась, что нужно ОЧИСТИТЬ строку поиска и наконец-то увидела хоть какие-то предложения, я перешла на детальную карточку, потом кликнула в браузере Назад и, о чудо, у меня опять нет ни одного предложения, а в строке поиска стоит давно стертое значение.

**Comment by Igorbek** [comment]
что должно произойти?

**Comment by StepanOvchinnikov** [comment]
я не придумал. закрываю
