### ISSUE TITLE
видно как исчезают предложения

### ISSUE THREAD

**Issue by olga7** [vfedyanov/rosobmen#107]
при переходе на страницу с предложениями я вижу как исчезают предложения - первая мысль, все сломалось.

**Comment by Igorbek** [comment]
более подробно описание хочется как воспроизвести.

**Comment by StepanOvchinnikov** [comment]
речь идет о визуальном эффекте появления предложений при выводе списка. 
http://shot.qip.ru/00dQu8-619gZJGWl7/

этот эффект при изменении фильтра или уходе со страницы выводится "наоборот" -- все улетает

**Comment by vfedyanov** [comment]
Закрываем
