### ISSUE TITLE
Не понимаю как работает список с категориями

### ISSUE THREAD

**Issue by irinameller** [vfedyanov/rosobmen#110]
http://shot.qip.ru/00q1PP-6gbw3doSk/

**Comment by Igorbek** [comment]
Такую верстку дали.

**Comment by StepanOvchinnikov** [comment]
нет, Игорь, там проблема в том что дерево выводится неверно. категории с подкатегориями перепутаны

**Comment by Igorbek** [comment]
сейчас они выглядят нормально.
