### ISSUE TITLE
На странице Регистрация еще не завершена нужно выводить адрес почты, на которую отправлена ссылка

### ISSUE THREAD

**Issue by a-davydov** [vfedyanov/rosobmen#123]
http://rosobmen.com/Account/Register
человек может ошибиться в адресе, и тогда на этой странице поймет
и не будет часами ждать письмо на правильную почту

**Comment by a-davydov** [comment]
То же можно и на странице Регистрация завершена
http://rosobmen.com/Account/ConfirmEmail?userId=7d01191e-027c-4ac3-85d3-1b04697c2fb7&code=rL%2Bh%2Bn95qb%2BYHye7qw1rjg1xzzAJILJq%2FJVyJPK3GZT%2FygVnZXJAfKRtoDLSiJhdDXyz2S7EXGpV5otEpbvi9BjufHHMijQKEPFwGAD3FHuP1kNw7ljLr%2BSLc2KPaCq3WJHLS%2FK95t%2FKYa5VvMADiA61COWaTZPuck5OqVytxt6EZpreBKIH6TU0Jef4l8yE

**Comment by vfedyanov** [comment]
Игорь, простая доделка?
