### ISSUE TITLE
Длинный логин липнет к краю

### ISSUE THREAD

**Issue by gorelovserj** [vfedyanov/rosobmen#129]
![image](https://cloud.githubusercontent.com/assets/8445531/3916203/8acf2980-2375-11e4-8019-91ca54d3695a.png)

**Comment by Igorbek** [comment]
Такая верстка. Ставлю на @StepanOvchinnikov

**Comment by StepanOvchinnikov** [comment]
решение: обрезать после 15 символа и поставить ...
