### ISSUE TITLE
Перешёл по категории с главной страницы "Музей эйнштэйна", а в каталоге пусту

### ISSUE THREAD

**Issue by gorelovserj** [vfedyanov/rosobmen#130]
Привяжите ссылки к каталогу. Если в каталоге ничего нет - прячьте ссылку

![image](https://cloud.githubusercontent.com/assets/8445531/3916212/b775171a-2375-11e4-9502-b686bf43468c.png)

**Comment by Igorbek** [comment]
Эти ссылки статические.
