### ISSUE TITLE
Проверка телефона в форме редактирвоания пользователя

### ISSUE THREAD

**Issue by gorelovserj** [vfedyanov/rosobmen#132]
Если вводишь мало цифр - проверяет и говорит, что с полем что-то не так.
Если больше чем надо - сохраняется

http://rosobmen.com/Manage#profile/edit

![image](https://cloud.githubusercontent.com/assets/8445531/3916232/270a28f4-2376-11e4-8d5d-aa43f75f5ed0.png)

**Comment by vfedyanov** [comment]
Игорь, ты подправил это? может ограничить ввод в 10 цифр (надо об этом написать в лейбле " Телефон (10 цифр)"

**Comment by Igorbek** [comment]
Это сделано. Только 11 цифр. Люди обычно пишут в таких форматах:
8 (код 1 цифра) 9... (номер 10 цифр) = 11
+7 (код 1) 9.... (номер 10) = 11
Я сделал чтобы ровно 11 цифр, опциональный `+` в начале и любое кол-во пробелов в середине.
