### ISSUE TITLE
Движение по счёту пользователя - странно заполняется колонка с датой

### ISSUE THREAD

**Issue by gorelovserj** [vfedyanov/rosobmen#134]
![image](https://cloud.githubusercontent.com/assets/8445531/3916300/f9c3c3ee-2377-11e4-81f0-0a1b7603a26a.png)

Через несколько секунд - потом чтоль?

**Comment by Igorbek** [comment]
Какой-то странный рассинхрон времени. Посмотрим. Дубль #63
