### ISSUE TITLE
не подтверждается номер телефона

### ISSUE THREAD

**Issue by navile** [vfedyanov/rosobmen#135]
http://www.rosobmen.com/Manage#profile

http://shot.qip.ru/00rd5w-69EAwnjmV/

**Comment by Igorbek** [comment]
А смс пришло? Что-нить в консоли пишет?

**Comment by navile** [comment]
Пришло смс. Вводим и нечего не происходит. Запрос выслать повторно..http://shot.qip.ru/00rd5w-69EAwnjw1/ . приходит смс, но не подтверждается.
И еще вопрос . А почему код всегда один и тот же приходит?

**Comment by Igorbek** [comment]
Очень странно. А во время ввода кода что говорит? Есть какая-то ошибка в консоли?

**Comment by navile** [comment]
Ничего не говорит.. просто остается неизменным

**Comment by Igorbek** [comment]
@StepanOvchinnikov @vfedyanov можете помочь достать технические детали проблемы?

**Comment by StepanOvchinnikov** [comment]
Наталья, дай мне свой логин-пароль и код, который приходит и не подтверждается

**Comment by navile** [comment]
Это мне вопрос?

С уважением,
Лепнухова Наталья
+7 9610724499

1 сентября 2014 г., 14:44 пользователь StepanOvchinnikov <
notifications@github.com> написал:

**Comment by StepanOvchinnikov** [comment]
Тебе. я был уверен что navile -- Оксана

**Comment by navile** [comment]
да нет!
Там уже эту ошибку снять можно. Ее вроде закрывали
я сегодня по новой планирую по ТЗ все пройтись.

С уважением,
Лепнухова Наталья
+7 9610724499

2014-09-01 15:20 GMT+04:00 StepanOvchinnikov notifications@github.com:

**Comment by Igorbek** [comment]
@StepanOvchinnikov следи за задачей

**Comment by vfedyanov** [comment]
Наталья, я закрываю по твоему указанию
