### ISSUE TITLE
не загружается полностью каталог

### ISSUE THREAD

**Issue by navile** [vfedyanov/rosobmen#138]
Есть картинка текста нет
http://shot.qip.ru/00rd5w-59EAwnjn0/

**Comment by Igorbek** [comment]
Какой браузер?
@StepanOvchinnikov переадресую верстальщику.

**Comment by StepanOvchinnikov** [comment]
ждем ответа о браузере и ссылку.

**Comment by navile** [comment]
http://rosobmen.com/Catalog
Chrom
http://shot.qip.ru/00stRM-5A3UbvKdo/
http://shot.qip.ru/00stRM-5A3UbvKdp/

**Comment by Igorbek** [comment]
дубль #145
