### ISSUE TITLE
Личный кабинет: странные кнопки, нет функций, орфография

### ISSUE THREAD

**Issue by StepanOvchinnikov** [vfedyanov/rosobmen#14]
http://shot.qip.ru/00dQu8-619gZJGVyn/
1. Я уже заполнил
2. нет смены пароля
3. ошибка в слове "контактные". доступ к правке языковых констант решает вопрос сразу

**Comment by Igorbek** [comment]
1. подробности, плз. когда такое происходит? сейчас не воспроизводится.
