### ISSUE TITLE
при отправки на  доработку, писать где- то хотелось бы что именно надо даработать

### ISSUE THREAD

**Issue by navile** [vfedyanov/rosobmen#140]
http://shot.qip.ru/00stRM-6A3UbvJGI/ - когда нажимаешь редактировать оно автоматом сворачивается и все http://shot.qip.ru/00stRM-5A3UbvJGJ/

**Comment by vfedyanov** [comment]
Игорь, Редактирование некорректно работает?

**Comment by Igorbek** [comment]
проверил - работает нормально.
