### ISSUE TITLE
При переходе по ссылке с первого экрана ничего не отображается

### ISSUE THREAD

**Issue by antonkarpov33** [vfedyanov/rosobmen#143]
[LINK:shot.qip.ru|http://shot.qip.ru/00sSvi-62yrTZ7Ne/]

**Comment by Igorbek** [comment]
Максимум через несколько секунд после перехода должно появиться. @antonkarpov33 перепроверьте, пожалуйста.

**Comment by vfedyanov** [comment]
непонятно, без комментариев от Антона. ЗАкрываю.
