### ISSUE TITLE
Наползание плиток в каталоге

### ISSUE THREAD

**Issue by antonkarpov33** [vfedyanov/rosobmen#145]
[LINK:shot.qip.ru|http://shot.qip.ru/00sSvi-62yrTZ7Ng/]

**Comment by Igorbek** [comment]
Какой браузер? URL страницы? В каких случаях происходит (всегда?)?

**Comment by vfedyanov** [comment]
Не знаю что у Антона, а вот у меня: https://yadi.sk/i/tsp3KBYcav3F4.
Порядок действий такой: поиском перешел в каталог, очистил поиск, выбрал в комбо товары+услуги. Получил это.

**Comment by antonkarpov33** [comment]
Гугл Хром. Не всегда. Если несколько раза выйти-зайти в каталог плитки отображаются нормально.

**Comment by vfedyanov** [comment]
Игорь, ты напиши Степану про проблему.
Он все ждет.

**Comment by Igorbek** [comment]
ну здесь смысл в том, что компонент делает расстановку сразу, а картинки грузятся позже, в связи с чем они и налезают.
у меня тут возникла мысль как это порешать. займусь. если что - отпишусь.
