### ISSUE TITLE
ввести ограничение по размеру блоков в каталоге , по символам  и предложение клиентам обрезать фото под аватарку

### ISSUE THREAD

**Issue by navile** [vfedyanov/rosobmen#148]
Нереально длинные и большие предложения в каталоге..
http://shot.qip.ru/00stRM-5A3UbvKdq/

**Comment by Igorbek** [comment]
Может, это должен контролировать модератор при размещении?

**Comment by vfedyanov** [comment]
Степану переведешь?

**Comment by navile** [comment]
переведу.
как в fb или в контакте или в любой другой соц сети.. когда загружаешь фото то оно по любому обрезается под аватарку. Нам нужно просто дать более точные размары. 
плюс количество символов которое печатается в услуге должно быть ограничено, например не более 100 символа, чтобы не было простыней на пол странице.
Насколько я помню мы делали по примеру http://shot.qip.ru/00stRM-5A3UbvKrU/
Но у нас почему то выглядит вот так http://shot.qip.ru/00stRM-5A3UbvKrV/
Много нерационального использования пространсства.
Мне кажется под картинкой должно быть просто описание услуги и  далее ограничение по символам как в твитере

**Comment by vfedyanov** [comment]
Степан?

**Comment by StepanOvchinnikov** [comment]
ограничить название 50 символом, описание 200. потом многоточие.
залезание названия под % постараемся исправить, дадим изменение верстки

**Comment by StepanOvchinnikov** [comment]
.margin-right-60{
margin-right: 60px
}
[10:53:24] Артем Звездилин: Для заголовка перед которым нет картинки
