### ISSUE TITLE
не по- русски формулировка в личном кабинете при перечислении купонов

### ISSUE THREAD

**Issue by navile** [vfedyanov/rosobmen#149]
как то не сразу понятно что и как к купону     http://rosobmen.com/Manage#coupons
Написано в столбце дата покупки   "14 дней назад
истекает через 2 месяца" http://shot.qip.ru/00stRM-5A3UbvKdv/
Задумавшись поняла что истекает через 2 месяца надо переместить в отдельный столбец и назвать столбец - срок действия и там поставить дату

**Comment by vfedyanov** [comment]
Игорь, это справедливо. Акцепт?

**Comment by Igorbek** [comment]
ну что значит справедливо? моя реализация тоже справедлива =) это доп.

**Comment by vfedyanov** [comment]
Окей, доп, закрываю.
