### ISSUE TITLE
Валидация полей в профиле: ИП, ИНН, КПП, орг-прав-форма

### ISSUE THREAD

**Issue by StepanOvchinnikov** [vfedyanov/rosobmen#15]
http://shot.qip.ru/00dQu8-619gZJGVyo/
1. Физ-Юр не совсем адекватно. ИП - физлицо, но с расчетным счетом. это холивар, предлагаю сделать вариант "ИП" с необязательным КПП
2. ИНН почему-то проверился только при втором входе. там был пробел
   вообще вся валидация при первом вводе не сработала
3. тексты валидаций -- перевести или (лучше) дать доступ

**Comment by Igorbek** [comment]
2, 3 закрыты. 1 подумайте

**Comment by StepanOvchinnikov** [comment]
# мнение юриста

Согласно идеологии Рособмена, пользователями могут быть и юр лица, и ип и физики.
   Отличие юрика от ип - у ип нет КПП и не всегда есть ОКПО. Также у ип может не быть печати и банковских счетов, то есть ОКПО и банковские счета можно делать необязательными полями.
    А у физика должно быть ИНН плюс паспортные данные

#     Кстати количество символов ИНН физика / ип (12) отличается от кол-во ИНН юрика (10)

давайте так и сделаем.
1. добавляем вариант "ИП" с описанными требованиями к полям
2. более простой вариант:
делаем 
"Юридическое лицо или ИП"
где КПП и ОКПО  делаем необязательными полями
Полное наименование => Полное наименование (для ООО) или ФИО (для ИП)
Сокращенное наименование — тоже необязательным
банк предлагаю оставить обязательным -- нам с людьми безналом работать, и а ИП-шник без счета -- редкость редкая
подправить валидатор для ИНН чтобы брал и 10 и 12 цифр

Я готов на второй. Это минимальное отхождение от ТЗ.
если в наших отношениях с ИП и ООО есть какие-то серьезные отличия, придется все же делать новую сущность "ИП". но я не вижу таких отличий.

**Comment by vfedyanov** [comment]
Игорь, принято?

**Comment by Igorbek** [comment]
Так и какой вариант делать? 1 или 2? Ну 2-й проще, очевидно.
Когда сделаю, старая база упадет - изменение в структуре базы т.к. потребуется.

**Comment by vfedyanov** [comment]
2 й вариант.
Сорри, не подтвердил

понедельник, 22 сентября 2014 г. пользователь Igor Oleinikov написал:

> Так и какой вариант делать? 1 или 2? Ну 2-й проще, очевидно.
> Когда сделаю, старая база упадет - изменение в структуре базы т.к.
> потребуется.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Igorbek/rosobmen/issues/15#issuecomment-56325928.

## 

Send by iPAD.
Владимир Федянов,
+79610695005
