### ISSUE TITLE
в личном кабинете должно стоять не сколько дней назад выставлен счет, а дата покупки или проведения операции

### ISSUE THREAD

**Issue by navile** [vfedyanov/rosobmen#150]
http://shot.qip.ru/00stRM-5A3UbvKdx/

18 дней назад написано. Это мне надо взять календарь и посчитать.

**Comment by vfedyanov** [comment]
Так, давайте это обсудим.
Игорь, пока не торопись.

**Comment by Igorbek** [comment]
обсуждайте.

**Comment by vfedyanov** [comment]
Принято решение по датам.
Игорь, тебе спасибо за модерновый способ вывода даты.

Что мы решили: 
1) если смысл "осталось ХХ дней" -- то писать текстом что осталосб ХХ дней
2) если смысл в том когда была сделана запись, то выводить ее датой

**Comment by vfedyanov** [comment]
Обсуждено, это мы с тобой проговаривали давным-давно. Акцепт?
