### ISSUE TITLE
новый пользователь, а у него куча оповещений

### ISSUE THREAD

**Issue by navile** [vfedyanov/rosobmen#153]
Зарегистрировала нового пользователя, а у него уже есть оповещения
http://rosobmen.com/Manage#notifications
http://shot.qip.ru/00stRM-6A3UbvKeC/

**Comment by Igorbek** [comment]
Уверены, что это новый пользователь и с ним зашли в систему? Это navile@yandex.ru? Он зарегистрирован 2 сентября.

**Comment by navile** [comment]
Ну с данного пользователя ничего не покупалось это точно.
Хотя могу ошибаться.

С уважением,
Лепнухова Наталья

**Comment by vfedyanov** [comment]
Наталья подтвердила -- проблема есть.

**Comment by Igorbek** [comment]
на скрине нет покупок - продажа, одобрение размещения и окончания срока размещения. с этого акка есть размещения. Как раз эти 2 услуги, что на скрине. Еще раз проверяйте.

**Comment by vfedyanov** [comment]
Наталья, ждем твоего ответа.

**Comment by navile** [comment]
Прошу обратить внимание, что
услуги в заявленной ошибке 21 день назад размещены http://shot.qip.ru/00stRM-6A3UbvKeC/. И до того как размещены текущие услуги у данного клиента,http://shot.qip.ru/00stRM-6A3UbvKOu/, а именно 14 дней назад
http://rosobmen.com/Manage#notifications

Это был какой-то глюк.
Главное чтобы он не были системным или систематическим.

**Comment by vfedyanov** [comment]
Наташа, убедительно и информативно

**Comment by Igorbek** [comment]
Ответа нет, закрываю.
