### ISSUE TITLE
нет итого по счету пользователя под администратором

### ISSUE THREAD

**Issue by navile** [vfedyanov/rosobmen#154]
Под администратором в счетах пользователя отсутствует итоговый баланс
http://shot.qip.ru/00stRM-6A3UbvKeE/

http://rosobmen.com/Manage/Admin#account?id=8698de12-b238-4cb6-af8b-618875c16c8e

**Comment by Igorbek** [comment]
хм.... такая штука. существует много чего показывать: +/-, актив/пассив, ПБ/р. Поэтому только показываю, если есть изменения. Если нет - скрывается.
На примере - в сумме все 0. Поэтому скрыто.
Показывать?

**Comment by vfedyanov** [comment]
Показывать всегда. Сделай плиз.

**Comment by vfedyanov** [comment]
Это обсудили. Акцепт?
