### ISSUE TITLE
не нашла пункт  из ТЗ в админке  по просмотру транзакций и купонов

### ISSUE THREAD

**Issue by navile** [vfedyanov/rosobmen#156]
http://shot.qip.ru/00stRM-6A3UbvKeG/

Админки должен существовать доступ к просмотру всех незавершенных транзакций (купленные, но не использованные купоны, а также передаваемые ПБ) с отображением следующей информации: ИНН, ФИО и название обоих контрагентов, дата начала транзакции, статус, ожидается ли модерация, сумма в ПБ или деньгах, доступен переход к модерации

**Comment by vfedyanov** [comment]
несоответствие ТЗ

**Comment by Igorbek** [comment]
Админка, меню "переводы".
