### ISSUE TITLE
при клике на капчу при регистрации выходит сайт  http://captcha.com/asp.net-captcha-info.html

### ISSUE THREAD

**Issue by navile** [vfedyanov/rosobmen#157]
Это зачем то надо??
нечаянно нажала на картинку капчи http://shot.qip.ru/00stRM-5A3UbvKeH/
и открылось в новой странице вот это http://shot.qip.ru/00stRM-5A3UbvKeI/

**Comment by vfedyanov** [comment]
Степан, что скажешь?

**Comment by StepanOvchinnikov** [comment]
это неправильно, так быть не должно
нам не нужна такая ссылка

Игорь, это использованный тобой капча-плагин?  ты можешь выпилить с него ссылку? хотя бы js вставить который убьет тег А из него?

приоритет низкий, беды никакой, но это явно неправильно
