### ISSUE TITLE
в админке не везде есть возврат в предыдущую страницу

### ISSUE THREAD

**Issue by navile** [vfedyanov/rosobmen#158]
http://shot.qip.ru/00stRM-6A3UbvKeK/
http://shot.qip.ru/00stRM-6A3UbvKeL/
http://shot.qip.ru/00stRM-5A3UbvKeM/
http://shot.qip.ru/00stRM-6A3UbvKeN/
http://shot.qip.ru/00stRM-5A3UbvKeO/

**Comment by Igorbek** [comment]
Страницы, которые доступны из меню слева не должны иметь возврат.
Какие из этих страниц внутренние?

**Comment by navile** [comment]
Я имею ввиду все станицы подменю слева. Когда в них заходишь, не везде есть кнопка возврат.
например, захожу в пользователи, и как вернуться на предыдущую страницу?

**Comment by vfedyanov** [comment]
Так, я закрываю тикет. Пока это роскошь, в бразузере есть кнопка назад.
