### ISSUE TITLE
Переработка системы ввода скидки клиентом

### ISSUE THREAD

**Issue by vfedyanov** [vfedyanov/rosobmen#162]
Игорь, смотри, важный момент. несоответствие ТЗ.

1) У нас по ТЗ клиент сам себе скидку не задает.
2) Но у нас по ТЗ ее может устанавливать модератор. Это самое главное, это нужно обязательно.

И когда у нас работает 1, у нас, можно сказать,  2 становится лишним. 2 Можно оставить, а можно убрать.
1 -- нужно обязательно.

**Comment by Igorbek** [comment]
Какая скидка? При оплате рублями? Я что-то не понял. Поясни.

**Comment by vfedyanov** [comment]
Да, скидка при оплате рублями. Виноват.
У нас по тз есть такое слово "дисконт". Речь про него.

**Comment by Igorbek** [comment]
Правильно ли понимаю, что только администратор устанавливает размер скидки?

**Comment by vfedyanov** [comment]
Согласно ТЗ -- да.
Вообще, для развития и некоторых идей сейчас можно оставить ввод и клиентом.
Но главное, именно цена установленная/отредактированная администратором предлагается для продажи.

**Comment by Igorbek** [comment]
Ну тогда все есть. Администратор может менять при модерировании как хочет. А после принятия, пользователь уже никак не может менять. Закрываем?

**Comment by vfedyanov** [comment]
пользователь не может менять никак.
Только тогда по умолчанию скидка 0%, окей?
И закрываем.

18 сентября 2014 г., 1:37 пользователь Igor Oleinikov <
notifications@github.com> написал:

**Comment by Igorbek** [comment]
Мне только непонятно. Сколько продавец получает ПБ при оплате рублями. Мы это обсуждали вроде - ты сказал, что сколько руюлями платят, столько и на счет продавцу в ПБ. Тогда как администратор имеет право ставить скидку?

**Comment by vfedyanov** [comment]
В ПБ он получает полное количество, безо всяких скидок.
То есть для продавца ситуация ТОЧНО такая, словно у него купили за ПБ.
Вообще без разницы.

18 сентября 2014 г., 1:40 пользователь Igor Oleinikov <
notifications@github.com> написал:

**Comment by Igorbek** [comment]
ага.... а говорил по-другому. и сделано по-другому.

**Comment by vfedyanov** [comment]
Как же? Ты же говорил что именно так и реализовал это

четверг, 18 сентября 2014 г. пользователь Igor Oleinikov написал:

> ага.... а говорил по-другому. и сделано по-другому.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Igorbek/rosobmen/issues/162#issuecomment-55965176.

## 

Send by iPAD.
Владимир Федянов,
+79610695005
