### ISSUE TITLE
каталог, порядок размещения предложений

### ISSUE THREAD

**Issue by navile** [vfedyanov/rosobmen#165]
предложением услуг в системе.
4.2.Просмотр услуг осуществляется по-умолчанию общим списком по дате размещения начиная с самых ранних.

а как определить что он именно так размещается.
Чисто визуально зная кто и когда размещал предложения , если зайти без регистрации то он стоит фильтром с самых дешевых
http://shot.qip.ru/00stRM-6A3UbvKOQ/

PS куда то делся крайний столбец. в идеале их вообще должно быть 4,( столбца...)

**Comment by Igorbek** [comment]
В верстке были даны 3 кнопки:
- дешевле - сортирую по возрастанию цены
- дороже - сортирую по убыванию цены
- новые - сортирую по убыванию даты публикации

добавлять кнопку "старые" ?

**Comment by navile** [comment]
Нет не нужно добавлять
