### ISSUE TITLE
Из Админки должен существовать доступ к просмотру всех незавершенных транзакций ТЗ: п9.2.2.

### ISSUE THREAD

**Issue by navile** [vfedyanov/rosobmen#166]
Где это искать?
Я искала здесь:
http://shot.qip.ru/00stRM-5A3UbvKOR/
Из Админки должен существовать доступ к просмотру всех незавершенных транзакций (купленные, но не использованные купоны, а также передаваемые ПБ) с отображением следующей информации: ИНН, ФИО и название обоих контрагентов, дата начала транзакции, статус, ожидается ли модерация, сумма в ПБ или деньгах, доступен переход к модерации

**Comment by Igorbek** [comment]
Повтор.
