### ISSUE TITLE
п 9.2.5 не нашла кнопку

### ISSUE THREAD

**Issue by navile** [vfedyanov/rosobmen#168]
Из Админки должен существовать доступ к списку всех транзакций (купонов и перемещений ПБ) для их просмотра и удаления по пользователю через список пользователей аналогичный предыдущему пункту

**Comment by navile** [comment]
и далее до  п. 9.3.6.

**Comment by Igorbek** [comment]
Доступ ко всем операциям у администратора есть через счета пользователей.
