### ISSUE TITLE
п 9.5.1.-п.9.5.4  хотела добавить пользовательское соглашение.... 

### ISSUE THREAD

**Issue by navile** [vfedyanov/rosobmen#169]
не добавила http://shot.qip.ru/00stRM-5A3UbvKOT/.. не знаю куда.

вот оно

https://docs.google.com/document/d/1eDV4vaccNAmJ9fWyqZNnP-kfzXnOtcm-oRmSCjZyVjY/edit?usp=sharing

**Comment by Igorbek** [comment]
Редактируется в настройках или в файле.

**Comment by Shtirhunov** [comment]
Добрый день,
соглашение на сайт так и не выложено. Кто можето это сделать. Если Админ, то каким образом?
