### ISSUE TITLE
не переводятся ПБ на счет другого пользователя и другие вопросы по переводу

### ISSUE THREAD

**Issue by navile** [vfedyanov/rosobmen#170]
жму на кнопку и ничего не происходит...
http://shot.qip.ru/00stRM-5A3UbvKOU/

**Comment by vfedyanov** [comment]
От Алисы:
11 нажимая на ссылки ничего не меняется, не понимаешь - нажал или нет, переведется отсюда туда или наоборот
![11 -](https://cloud.githubusercontent.com/assets/8436576/3903258/c71ebe84-22c9-11e4-9144-736d99174ca8.png)

**Comment by vfedyanov** [comment]
Игорь, это из той же области?
От Алисы:
13 ничего не меняется при нажатии обновить
![13](https://cloud.githubusercontent.com/assets/8436576/3903261/c7364086-22c9-11e4-98a0-e851fbf9e9bd.png)

**Comment by vfedyanov** [comment]
От Алисы:
21  пусто, хотя есть же операции перевода уже пробные
![21](https://cloud.githubusercontent.com/assets/8436576/3903267/c775b14e-22c9-11e4-8847-e5b49bcf8e95.png)

**Comment by Igorbek** [comment]
Проверил, операции перевода работают. Баги описывайте подробно как воспроизвести.
