### ISSUE TITLE
Алиса: подтверждение покупки

### ISSUE THREAD

**Issue by vfedyanov** [vfedyanov/rosobmen#173]
5 для чего эта кнопка? нажимаю ничего не происходит, я выбрала способ оплаты через оператора мтс, далее все операции с ним
![5](https://cloud.githubusercontent.com/assets/8436576/3903251/c6f57efc-22c9-11e4-81cf-ae2948c6552e.png)

**Comment by vfedyanov** [comment]
Степан, а как правильно?

**Comment by StepanOvchinnikov** [comment]
дальше должен открыться диалог оплаты, куда вводится ключ из смс

если баг не повторяется, можно закрыть

**Comment by vfedyanov** [comment]
Попроси Алису его воспроизвести, хорошо?

**Comment by StepanOvchinnikov** [comment]
попросил

**Comment by StepanOvchinnikov** [comment]
[12:09:57] Алиса Колесникова: Степан, тоже самое- нажала "продолжить", страница моргнула, пришла смс, а визуально страница никак не изменилась
[12:10:26] Алиса Колесникова: после подтверждения страница неистово моргает

**Comment by StepanOvchinnikov** [comment]
т.к. оплата почему то не прошла
аа, блин, потому что я опять в минус влезла
но страница моргает и обновляется это нехорошо

**Comment by vfedyanov** [comment]
А как должно быть, Алиса, посоветуй.

среда, 24 сентября 2014 г. пользователь StepanOvchinnikov написал:

> т.к. оплата почему то не прошла
> аа, блин, потому что я опять в минус влезла
> но страница моргает и обновляется это нехорошо
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Igorbek/rosobmen/issues/173#issuecomment-56638191.

## 

Send by iPAD.
Владимир Федянов,
+79610695005

**Comment by StepanOvchinnikov** [comment]
должно быть уведомление "у вас баланс отрицательный".
и не пускать к оплате

**Comment by Igorbek** [comment]
Я что-то вообще это не вкурил. Вы реально считаете, что этот баг на мне? Т.е. мне нужно сделать на робокассе фикс, который запрещает оплату, когда на телефоне отрицательный баланс? :=)

**Comment by StepanOvchinnikov** [comment]
хм. я так понял речь о балансе на рособмене.
но ты прав, да.
тупняки робокассы не про тебя
