### ISSUE TITLE
Алиса: косметические замечания

### ISSUE THREAD

**Issue by vfedyanov** [vfedyanov/rosobmen#175]
19 то капсом, то нет
![19](https://cloud.githubusercontent.com/assets/8436576/3903265/c75d2b38-22c9-11e4-97e7-cfadc17c0e73.png)

18 пробел бы
![18](https://cloud.githubusercontent.com/assets/8436576/3903264/c74e4f3c-22c9-11e4-87c0-3cfaa76c1624.png)

**Comment by Igorbek** [comment]
Так это строка с общим. Я использовал tfoot у таблицы, а капс был в верстке.

**Comment by vfedyanov** [comment]
Понял :) но это не очевидно при наличии одной строки :) можем ли мы написать ВСЕГО или ИТОГО ?

**Comment by Igorbek** [comment]
ну там так и написано =) только слева.
