### ISSUE TITLE
Скомпилировать less

### ISSUE THREAD

**Issue by Igorbek** [vfedyanov/rosobmen#177]
Для задач #102, #93, #59 нужен измененный css на основе less.
Тот, что есть у меня (смотрите в основном репозитории), дает некорректный выходной css, что вызвало вот это Igorbek/plazma#161.

Прошу предоставить
- корректный выходной css
- нормальный полный комплект less (опционально, при желании)

**Comment by shkarupa-alex** [comment]
Вот тут мой комментарий https://github.com/Igorbek/rosobmen/issues/93 с информацией что делать чтобы полечить проблему

**Comment by Igorbek** [comment]
Проблема не эта, а то, что выходной файл получается некорректный. Куча ссылок на неправильные пути.
Просто сделайте свою задачу. @StepanOvchinnikov @vfedyanov давайте, подключайтесь.

**Comment by Igorbek** [comment]
Вот так вот получилось в результате:
![image](https://cloud.githubusercontent.com/assets/1929486/4454290/5b4e3602-486d-11e4-9367-71f9354573b5.png)

**Comment by StepanOvchinnikov** [comment]
Игорь, после последнего раза когда мы компилировали less, было сделано много мелких изменений, списка которых у нас нет и последней версии, соответственно, тоже.
Точка сборки верстки сейчас не у нас.

Предыдущие разы компиляция удавалась?
Что не удается сейчас конкретно?
Какие ошибки, где, после каких правок?

**Comment by Igorbek** [comment]
Ну я less как бы ни разу и не собирал. Изначально верстка давалась мне без less, только css. Я less попросил, чтобы в репе было. Мне прислали архивчик, я его и залил. Но вот компилируется он без ошибок, но с кучей нарушенных путей к картинкам и шрифтам. Т.е. какие-то у вас настройки еще есть.
Результирующий css ты можешь посмотреть здесь: https://github.com/Igorbek/plazma/blob/67e7ec2ee1fd43c3308cd84a260cfcd8427b0fdb/src/Plazma/Plazma.Web/Content/template_styles.css

**Comment by StepanOvchinnikov** [comment]
Игорь, несколько вопросов, а то мы понять не можем
1. ты у нас less попросил 2 июля http://shot.qip.ru/00dQu8-619gZJGXWd/ 
потому что у ты на себя берешь процесс компиляции?
если да, почему сейчас надо чтобы компилировали мы?
1. если  (1) - нет, то мы уже давно отправляем тебе мелкие правки к less'у (не к css) и не копим их у себя, и ты молчишь. все было в порядке? ты сейчас впервые за долгое время взялся что-то скомпилировать?

Теперь факты
1. смотрю тот css который ты показал
при преобразовании из less не меняются пути. они были и остаются относительными
версии:
- ты инключишь какой-то файл с неправильными путями
- твои пути на сервере не те, что используются в изначальном less?
  в поддержку последней версии

смотрю то что сейчас на рособмене: http://shot.qip.ru/00dQu8-519gZJGXWg/
шрифты в каталоге font

смотрю то, что ты скомпилировал:http://shot.qip.ru/00dQu8-519gZJGXWh/
шрифты в каталоге fonts

Аналогично с картинками
пути просто другие
вот что на рособмене http://shot.qip.ru/00dQu8-519gZJGXWj/
вот что скомпилировано http://shot.qip.ru/00dQu8-519gZJGXWi/

Все различия решаются текстовой заменой.
fonts => font
less/tpl/img -> img
1. Та css, которую я сейчас вижу на рособмене, была выдана Артемом и адаптирована под вашу файловую структуру (у нас более сложная)
   http://rosobmen.com/Content/css?v=dFaUBSGVJlmq-hgaTryaFGquI_V9MR49q7HnHWjP0iQ1

Артем почти отсутствовал на работе последние 2 недели, поэтому правки, которые делались по твоей просьбе, делал Алексей Шкарупа на своей копии и отправлял тебе. Они не были совместимы.
Честно говоря, мы рассчитывали что обратная связь поступит сразу.

Нам будет весьма трудно собрать по тикетам все изменения и актуализировать их.
Сейчас самое простое решение: выполнить текстовые замены на less или на готовом css (скорее всего, других правок не будет, но если что -- пути определяются так).

**Comment by Igorbek** [comment]
Залил, смотрите и проверяйте задачи #102, #93, #59. Если все нормально - закрывайте.
