### ISSUE TITLE
задвоение фототоваров и услуг при входе в карточку услуги.

### ISSUE THREAD

**Issue by navile** [vfedyanov/rosobmen#178]
http://shot.qip.ru/00stRM-6A3UbvLY3/

фото задваивается во всех карточках товаров и услуг

**Comment by vfedyanov** [comment]
Бяка

**Comment by Igorbek** [comment]
Хм... ну вы не думали, что это верстка? Я поменял только скомпилированный less -> css. Может кто-нибудь из верстальщиков найти проблемное место в less/css. Раньше такого не было.

**Comment by shkarupa-alex** [comment]
В данном слайдере неверно прикручена верстка.

Вот как должно быть (http://test.ivserv1.tmweb.ru/rosobmen/product.html) https://www.evernote.com/shard/s303/sh/e696a455-e713-429e-9fab-bf60bb3bf81a/5dc73e02641d7c1285e1fb29ddef97db

А вот как есть https://www.evernote.com/shard/s303/sh/e1b69fb6-bed0-4aae-8074-b30b16d26085/6f68e578de38cc22a15c62ecd62645a3

Приведите html в правильный вид и тогда я смогу сказать что не так со стилями
