### ISSUE TITLE
Опять в хроме когда заполняешь контактные данные и делаешь сохранить ничего не происходит

### ISSUE THREAD

**Issue by navile** [vfedyanov/rosobmen#180]
http://shot.qip.ru/00stRM-6A3UbvM6w/
Тоже происходит и в каталоге
работаю с Хрома, с нормальной скоростью интернета

**Comment by Igorbek** [comment]
Починил в Igorbek/plazma@f7a2843c8e65ffcf353231da4da3c4d4959144d3
Заодно обзавелись (починил) сообщениями об ошибках.
