### ISSUE TITLE
разместить видео инструкцию

### ISSUE THREAD

**Issue by navile** [vfedyanov/rosobmen#182]
Прошу разместить видеоинструкцию
 http://youtu.be/cHBO5CPN-dQ
Разместить требуется на главной странице под ссылкой как это работает
http://shot.qip.ru/00stRM-5A3UbvMk1/

и в личном кабинете под ссылкой обзор
http://rosobmen.com/Manage#dashboard
http://shot.qip.ru/00stRM-5A3UbvMk7/

**Comment by Igorbek** [comment]
Давайте точный кусок HTML кода.

**Comment by StepanOvchinnikov** [comment]
точный код

<ob ject width="640" height="360"><param name="movie" value="//www.youtube.com/v/cHBO5CPN-dQ?hl=ru_RU&amp;version=3"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="//www.youtube.com/v/cHBO5CPN-dQ?hl=ru_RU&amp;version=3" type="application/x-shockwave-flash" width="640" height="360" allowscriptaccess="always" allowfullscreen="true"></embed></ob ject>

или

<ifr ame width="640" height="360" src="//www.youtube.com/embed/cHBO5CPN-dQ" frameborder="0" allowfullscreen></ifr ame>

любой какой заработает

это соответственно старый и новый коды с youtube

гит режет html
![code](https://cloud.githubusercontent.com/assets/8252959/4871435/723263d2-61b5-11e4-8214-3fc5edffcaf4.png)

вставил текстовый файл, переименовав его в png

ps а вообще этот код получается с ютуба в два щелчка: поделиться-html-код
