### ISSUE TITLE
сделать ссылки на главной странице чтобы уходили в каталог

### ISSUE THREAD

**Issue by navile** [vfedyanov/rosobmen#184]
прошу сделать ссылки на главной странице где идут ссылки на хештеги
и один хештег переименовать в каталог

http://shot.qip.ru/00stRM-6A3UbvMmV/

http://rosobmen.com/

**Comment by Igorbek** [comment]
Напишите конкретные ссылки куда.
Ссылка - Товар (url товара).

**Comment by navile** [comment]
http://rosobmen.com/catalog#list?searchQuery=%D0%A0%D0%B5%D0%BC%D0%BE%D0%BD%D1%82%20%D0%B0%D0%B2%D1%82%D0%BE - переименовать в КАТАЛОГ  и сделать ссылку http://rosobmen.com/Catalog
