### ISSUE TITLE
При заведении услуги в РОСОБМЕН НЕ сохраняются теги

### ISSUE THREAD

**Issue by Shtirhunov** [vfedyanov/rosobmen#186]

**Comment by vfedyanov** [comment]
Тэги добавляются по нажатию клавиши Enter и сохраняются. Тэги могут содержать пробелы.

**Comment by Shtirhunov** [comment]
Проверил, все работает.
 11 Дек 2014 г. 22:49 пользователь "vfedyanov" notifications@github.com
написал:
