### ISSUE TITLE
поля в услуге не по ТЗ

### ISSUE THREAD

**Issue by StepanOvchinnikov** [vfedyanov/rosobmen#19]
http://shot.qip.ru/00dQu8-519gZJGVys/

и вопрос на обсуждение http://shot.qip.ru/00dQu8-619gZJGVyt/

**Comment by Igorbek** [comment]
1. поля
   - категория есть
   - теги, админская на реализацию
2. в ТЗ обязательное, вроде.

**Comment by vfedyanov** [comment]
1. поле обязательно.
