### ISSUE TITLE
Закрытая задача по размещению пользовательского соглашения на самом деле не реализована!

### ISSUE THREAD

**Issue by iwanOV** [vfedyanov/rosobmen#190]
https://github.com/Igorbek/rosobmen/issues/169
Добрый день, коллеги!
Задача по размещению пользовательского соглашения на самом деле не реализована!
Когда можно ожидать её исполнения?

**Comment by vfedyanov** [comment]
Пользовательское соглашение размещено на сайте, но оно имеет незаполненные поля (подчеркнутые места).

**Comment by vfedyanov** [comment]
Коллеги! обратите внимание!!!
Там и директор -- Карпов!
Документ создан Натальей, поправьте его!

**Comment by iwanOV** [comment]
Хорошо

**Comment by vfedyanov** [comment]
Иван, офферта по ссылке обновлена, ее нужно срочно выложить https://docs.google.com/document/d/1eDV4vaccNAmJ9fWyqZNnP-kfzXnOtcm-oRmSCjZyVjY/edit
