### ISSUE TITLE
Баги, выявленные нашим сотрудником - Полиной

### ISSUE THREAD

**Issue by iwanOV** [vfedyanov/rosobmen#191]
Полина Суховилова -> Всем сотрудникам
Всем добрый день! 
Хочу написать о "багах" на нашем сайте. А именно: 
1. После того как от имени администратора я отправляю карточку на доработку и редактирование клиенту, от лица клиента эта же самая карточка почему-то не редактируется (отредактировав, жму "сохранить", ничего не происходит, попросту кнопка "сохранить" ничего не сохраняет). Таким образом приходится удалять карточки и заново их перезаливать. 
2. Предлагаю внести при заполнении карточки в пункт "срок действия сертификата" - "бессрочный". 
3. Если, к примеру, номинал одной услуги -1 рубль, то со скидкой 0,80 копеек в плазмабонусах внести тоже уже не получается (т.е. сайт не рассматривает наличие дробных чисел). 
Возможно описала не очень понятно, т.к. не совсем поняла сама еще работу на сайте.

**Comment by vfedyanov** [comment]
Все очень даже понятно.

1) Ошибка отмеченная Иваном, надо исправлять
2) Срок действия сертификата? или услуги?
3) Это вообще мне не нравится идеологически. как это 1 рубль? Это непонятно
покупателю. Это надо будет обсудить.

27 ноября 2014 г., 16:24 пользователь iwanOV notifications@github.com
написал:

**Comment by iwanOV** [comment]
2) Срок действия услуги.
3) Цена в один рубль нужна для набора точной суммы для оплаты за услуги, цена которых не круглая и непостоянная. Например за рекламу. На сайте сейчас, как и во всех интернет-магазинах, товар продаётся штуками, а у каждой штуки товара своя цена. 
Может быть можно реализовать возможность покупки товара (Услуги) на любую сумму?

**Comment by Igorbek** [comment]
1. исправил

**Comment by vfedyanov** [comment]
1. Готово
2. НЕЛЬЗЯ делать бессрочно услугу. Это нужно обсуждать и пока я знаю почему категорически НЕЛЬЗЯ.
3. Возможность покупки, в принципе-то да.... но давайте встречаться тоже. Сделайте пока по 100 рублей. Это нормально. Зачем вам сумма меньше? и тогда и в рублях сумма будет нормальной.

**Comment by vfedyanov** [comment]
Комментариев нет, закрываю
