### ISSUE TITLE
добавление услуги -- тупит

### ISSUE THREAD

**Issue by StepanOvchinnikov** [vfedyanov/rosobmen#20]
http://shot.qip.ru/00dQu8-519gZJGVyu/

**Comment by vfedyanov** [comment]
Игорь, почему долго? что можно сделать?

**Comment by Igorbek** [comment]
Сейчас все там бодро работает. Я этого не вижу.
Если и сейчас так, прошу тайминг сделать (например в хроме таймлайн взять).

**Comment by StepanOvchinnikov** [comment]
не тупит сейчас. закрываю
