### ISSUE TITLE
СЧЕТЧИК посетителей ресурса РОСОБМЕН

### ISSUE THREAD

**Issue by Shtirhunov** [vfedyanov/rosobmen#202]
Необходимо  "прикрутить" счетчик посетителей видный из админки.

**Comment by StepanOvchinnikov** [comment]
код счетчика



<a href="https://metrika.yandex.ru/stat/?id=24610916&amp;from=informer"
target="_blank" rel="nofollow"><img src="//bs.yandex.ru/informer/24610916/3_1_FFFFFFFF_EFEFEFFF_0_pageviews"
style="width:88px; height:31px; border:0;" alt="Яндекс.Метрика" title="Яндекс.Метрика: данные за сегодня (просмотры, визиты и уникальные посетители)" onclick="try{Ya.Metrika.informer({i:this,id:24610916,lang:'ru'});return false}catch(e){}"/></a>





<script type="text/javascript">
(function (d, w, c) {
    (w[c] = w[c] || []).push(function() {
        try {
            w.yaCounter24610916 = new Ya.Metrika({id:24610916,
                    webvisor:true,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true});
        } catch(e) { }
    });
    var n = d.getElementsByTagName("script")[0],
        s = d.createElement("script"),
        f = function () { n.parentNode.insertBefore(s, n); };
    s.type = "text/javascript";
    s.async = true;
    s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";
    if (w.opera == "[object Opera]") {
        d.addEventListener("DOMContentLoaded", f, false);
    } else { f(); }
})(document, window, "yandex_metrika_callbacks");
</script>

<noscript><div><img src="//mc.yandex.ru/watch/24610916" style="position:absolute; left:-9999px;" alt="" /></div></noscript>



нужно вставить на все страницы сайта в низ страницы
он стоял ранее, но сейчас не установлен нормально.

**Comment by StepanOvchinnikov** [comment]
продублировал Владимиру и Ивану на почту
