### ISSUE TITLE
Срочно!! Выгрузить оферту в редакции от 08.12.2014

### ISSUE THREAD

**Issue by Shtirhunov** [vfedyanov/rosobmen#206]
![08 12 2014 -page-001](https://cloud.githubusercontent.com/assets/9961638/5345526/6cc46102-7f29-11e4-968e-aab54fcfc1e2.jpg)
![08 12 2014 -page-002](https://cloud.githubusercontent.com/assets/9961638/5345529/6cd2d728-7f29-11e4-8102-51abb86d0d2c.jpg)
![08 12 2014 -page-003](https://cloud.githubusercontent.com/assets/9961638/5345528/6cd261b2-7f29-11e4-99e0-98d272504fbf.jpg)
![08 12 2014 -page-004](https://cloud.githubusercontent.com/assets/9961638/5345527/6ccef572-7f29-11e4-85ba-44720ff160af.jpg)
![08 12 2014 -page-005](https://cloud.githubusercontent.com/assets/9961638/5345530/6cd31a76-7f29-11e4-99f8-8ae7afa22c0c.jpg)

**Comment by vfedyanov** [comment]
Ребята, где текст? Офферту картинками не выложишь и не заакцептишь

**Comment by Shtirhunov** [comment]
ПУБЛИЧНАЯ ОФЕРТА

Российская Федерация

Город Волгоград 09 декабря 2014 года

Настоящим Общество с ограниченной ответственностью «СУММА ТЕХНОЛОГИЙ», именуемое далее «Общество», юридическое лицо по законодательству Российской Федерации, зарегистрированное в Едином государственном реестре юридических лиц за основным государственным регистрационным номером 1133443033448 заявляет, что действуя от имени и за счет Исполнителя как агент, будет считать себя заключившим Договор на условиях настоящей Оферты со всяким физическим лицом (далее «Клиент»), зарегистрированным на сайте в сети Интернет по адресу http://rosobmen.com/ и предоставившим Акцепт. 

I. ОПРЕДЕЛЕНИЯ.

1.1. Если иное не вытекает из настоящей оферты, нижеуказанные термины будут использоваться и применяться в следующих значениях:
- Сайт – интернет-сайт, принадлежащий Обществу и размещенный в сети Интернет по адресу http://rosobmen.com/.
- Публичная оферта (Оферта) – настоящий документ, опубликованный на Сайте, обращенный к неограниченному и неопределенному кругу лиц, содержащий предложение приобрести товары, работы или услуги Исполнителей в порядке, предусмотренном в Публичной оферте.
- Исполнители – индивидуальные предприниматели и юридические лица, зарегистрированные на Сайте, заключившие Договор возмездного оказания услуг с Обществом и представившие официальное публичное Предложение товаров, работ или услуг на Сайте.
- Клиенты – юридические и физические лица (включая индивидуальных предпринимателей), зарегистрированные на Сайте, заключившие договор на приобретение товаров, работ или услуг Исполнителя с Обществом, в том числе посредством акцепта Публичной оферты.
- Пользователи – Исполнители и Клиенты, зарегистрированные на Сайте.
- Идентификационный номер Пользователя – состоящий из цифр уникальный номер, присваиваемый Пользователю при регистрации на Сайте. 
- Акцепт оферты – полное и безоговорочное принятие Публичной оферты Клиентом путем осуществления регистрации на Сайте, осуществления оплаты за товары, работы или услуги Исполнителя, а также выполнения иных обязательных условий, предусмотренных Предложением Исполнителя и Публичной офертой.
- Предложение – перечень существенных условий договора на приобретение товаров, работ или услуг Исполнителя (включая наименование товара, работы или услуги, количество, стоимость, срок действия Предложения), определяемый Исполнителями и размещаемый на Сайте в разделе http://rosobmen.com/Catalog. Предложения являются неотъемлемой частью Публичной оферты.
- Личный кабинет – персональный раздел Пользователя на Сайте, при помощи которого можно осуществлять заказ и оплату товаров, работ или услуг, размещать Предложения, видеть информацию о текущем состоянии Счетов, включая зачисленные денежные средства и ПлазмаБонусы.
- Счет – виртуальный счет Пользователя в Личном кабинете, содержащий информацию о принадлежащих Пользователю денежных средствах и ПлазмаБонусах.
- ПлазмаБонус – виртуальная неденежная единица, подтверждающая право Клиента на приобретение товаров, работ или услуг Исполнителей со скидкой до 100 % включительно, количество которых отражается на Счетах Клиента на Сайте.
- Купон – документ, составляемый в свободной форме Обществом (но в обязательном порядке, содержащий в себе Индивидуальный номер, ФИО Клиента и если это указано в Предложении Исполнителя – Код бронирования или Пин-код), позволяющий определить факт заключения Клиентом с Обществом договора на приобретение товаров, работ или услуг Исполнителя, а также подтверждающий право Клиента на предоставление Исполнителем товара, работы или услуги в соответствии с условиями Предложения Исполнителя в его пользу. Купон может быть использован Клиентом единовременно и однократно. Купон, если иное не предусмотрено Предложением Исполнителя, должен быть распечатан Клиентом. После передачи Клиентом Купона Исполнителю, Купон считается использованным.
- Срок действия Купона - период времени, в течение которого Клиент вправе приобрести, а Исполнитель обязан предоставить товары, работы или услуги на условиях Предложения Исполнителя. Срок действия купона указывается на Сайте и на купоне.
- Код бронирования – уникальный цифровой код, состоящий из 3 (трех) символов, позволяющий определить факт обращения Клиента в адрес Исполнителя в целях резерва, заказа, бронирования товара, работы или услуги и заключение договора на приобретение товаров, работ или услуг Исполнителя. Код бронирования применяется в случае, если это прямо предусмотрено Предложением Исполнителя.
- Пин-код – уникальный цифровой код, состоящий из 4 (четырех) символов, позволяющий определить факт надлежащего предоставления Исполнителем товара, работы или услуги Клиенту по конкретному Купону и окончания всех обязательств между Исполнителем и Клиентом. После сообщения Клиентом Пин-кода Исполнителю, Купон считается использованным. С момента передачи Клиентом Пин-кода Исполнителю все обязательства Общества в качестве агента считаются полностью исполненными, а все возникшие претензии по качеству, количеству, ассортименту и порядку предоставления товара, работы или услуги урегулируются Исполнителем. Пин-код применяется в случае, если это прямо предусмотрено Предложением Исполнителя.
- Территория исполнения – территория, указанная в Предложении Исполнителя, в пределах которых Исполнитель обязуется исполнить свои обязательства по Предложению.
- Индивидуальный номер Купона – состоящий из цифр уникальный номер Купона.
- Цена – цена на товар, работу или услугу, установленная Исполнителем в Предложении.
- Код отправки - восьмизначный код, формируемый Сайтом при отправлении ПлазмаБонусов со счета Клиента-отправителя на счет Клиента-получателя, необходимый для передачи ПлазмаБонусов посредством ввода данного кода Клиентом-отправителем.
- Код получения - восьмизначный код, формируемый Сайтом при отправлении ПлазмаБонусов со счета Клиента-отправителя на счет Клиента-получателя, необходимый для завершения передачи ПлазмаБонусов посредством ввода данного кода Клиентом-получателем.

II. АКЦЕПТ ОФЕРТЫ.

2.2. Акцепт Оферты в порядке статьи 433 Гражданского кодекса Российской Федерации влечет и подтверждает заключение Договора на приобретение товаров, работ или услуг Исполнителя Клиентом (далее «Договор»), сторонами которого является Клиент и Общество, которое действует от имени и за счет Исполнителя.

2.2. Предмет, условия и срок действия Договора устанавливаются в соответствующем Предложении Исполнителя и настоящей Оферте. Предложения Исполнителя являются неотъемлемой частью Договора.

2.2. Подтверждением для Исполнителя факта заключения Клиентом Договора с Обществом (в зависимости от требований в Предложении Исполнителя) может являться:
- передача Клиентом Исполнителю Кода бронирования;
- передача Клиентом Исполнителю Пин-кода;
- передача Клиентом Исполнителю Купона;
- передача Клиентом Исполнителю заверенной Обществом копии договора между Клиентом и Обществом, если письменная форма договора является обязательным условием по размещенному Исполнителем Предложению;
- передача Клиентом Исполнителю документа, подтверждающего оплату товаров, работ или услуг Исполнителя на условиях соответствующего Предложения;

2.2. Порядок обмена информацией между Обществом и Клиентом, а также Клиентом и Исполнителем определяется и доводится до сведения Пользователей на Сайте.

2.2. Клиент согласен с тем, что Обществом используются и обрабатываются персональные данные Клиента. Персональные данные Клиента являются конфиденциальными и не подлежат разглашению или предоставлению любым третьим лицам, а также несанкционированному использованию. Клиент несет ответственность за сохранение конфиденциальности своих регистрационных данных на сайте (электронная почта и пароль), а также за все действия, осуществляемые с ними. Общество гарантирует Клиенту, что использование его персональных данных будет осуществляться Обществом только в целях надлежащего исполнения своих обязательств по настоящей Оферте.

2.2. Настоящим Клиент соглашается на передачу своих персональных данных Исполнителю. Ответственность за использование, сохранность, обработку персональных данных Клиента, полученных Исполнителем, несет Исполнитель.

2.2. Клиент согласен с тем, что после прохождения процедуры регистрации на Сайте на адрес электронной почты Клиента Обществом будут направляться письма и сообщения, в том числе рекламного характера. Вместе с тем Общество обязуется не передавать адрес электронной почты и иные сведения о Клиенте третьим лицам.

2.2. Клиент может в любой момент потребовать удаления предоставленных персональных данных, обратившись в Общество, направив письмо с соответствующим запросом на адрес электронной почты info@rosobmen.com . Обращаясь в Общество, Клиент обязуется действовать строго в соответствии с указаниями сотрудника Общества. Неисполнение Клиентом законных требований сотрудника Общества освобождает Общество от ответственности по требованиям Клиента до тех пор, пока не будут выполнены Клиентом необходимые требования.

III. ПРАВА, ОБЯЗАННОСТИ И ОТВЕТСТВЕННОСТЬ ОБЩЕСТВА.

3.3. Ответственность Общества ограничивается размещением на Сайте Предложений от имени и за счет Исполнителя, а также принятием денежных средств от Клиента, предоставлением Клиенту Купона, подтверждающего право требования Клиента товара, работы или услуги у Исполнителя в соответствии с условиями Предложения Исполнителя. Права и обязанности по Договору возникают непосредственно у Клиента и Исполнителя. Все претензии к предмету и условиям Договора, в том числе в отношении качества, количества и ассортимента товара, работы или услуги предъявляются Исполнителю.

3.3. Обязательства Общества по настоящей Оферте действительны в течение Срока действия Купона, если такой Купон Клиентом не использован.

3.3. Обязательства Общества по настоящему Договору считаются исполненными целиком и полностью (в зависимости от того, что наступит ранее):
- по истечению Срока действия Купона, если Клиент в течение этого срока не обратился в Общество за возвратом денежных средств за Купон;
- в случае использования Купона Клиентом.

3.3. Общество ни при каких обстоятельствах не несет ответственности по акцептированной Оферте за какие-либо действия или бездействия Исполнителя либо третьих лиц и не обязано возмещать какие-либо косвенные убытки или упущенную выгоду Клиента или третьих лиц вне зависимости от того, могло ли Общество предвидеть возможность таких убытков или нет.

3.3. Клиент не имеет право требовать с Общества взыскания либо удержания каких-либо сумм либо части таких сумм из средств, перечисленных Клиентом Исполнителю в счет оплаты за товары, работы или услуги Исполнителя. 

IV. ПРАВА, ОБЯЗАННОСТИ И ОТВЕТСТВЕННОСТЬ КЛИЕНТА.

4.4. Клиент обязуется перечислить сумму денежных средств в соответствии с условиями Предложения Исполнителя на счет Общества способами, предусмотренными соответствующим разделом Сайта «Покупка услуги за рубли» или «Покупка услуги за Плазма бонус». Перечисление денежных средств производится посредством безналичного расчета или с использованием ресурса ROBOKASSA.

4.4. Все расходы, связанные с оплатой товаров, работ или услуги несет Клиент или Плательщик, осуществляющий платежи от имени Клиента, в том числе комиссии платежных систем и иные расходы.

4.4. Указание номера телефона при регистрации в Личном кабинете является согласием Клиента получать СМС – сообщения информационного и рекламного характера. Для отказа от рассылки посредством СМС, Клиент должен обратиться в Общество, заполнить и передать заявление по форме Общества.

4.4. Клиент обязан указать свой действующий адрес электронной почты и контактный телефон при регистрации на Сайте. Эта информация используется в качестве канала обратной связи Общества с Клиентом. В случае предоставления Клиентом недействующего адреса электронной почты или контактного телефона, Общество не гарантирует выполнение обязательств Обществом и Исполнителями в полном объеме.

4.4. Осуществляя Акцепт Оферты, Клиент соглашается, что в течение Срока действия Купона решение о возврате денежных средств по Забронированным Купонам производится Обществом в соответствии с настоящей Офертой, если иное не указано в предмете и условиях Предложения Исполнителя.

4.4. Возврат денежных средств может быть осуществлен: 
- на Счет в Личном кабинете Клиента на основании заявления по форме Общества;
- на банковский счет, с которого была произведена оплата, при условии предоставления Клиентом необходимых реквизитов. В зависимости от банка-эмитента срок возврата денежных средств может происходить в течение 10 (Десяти) рабочих дней;
- путем отмены транзакции, если оплата товара, работы или услуги Исполнителя происходила с пластиковой карты. 

Запросы на возврат денежных средств рассматриваются только в течение Срока действия Купона и если товар, работа или услуга по Предложению Исполнителя не входят в Перечень, установленный Постановлением Правительства РФ от 19 января 1998 года № 55 либо иной нормативный акт, устанавливающий ограничения на возврат денежных средств.

4.4. Клиент осознает и подтверждает, что в случае передачи Исполнителю Пин-кода или Купона, Купон считается использованным, а Клиентом получен товар, работа или услуга. Все претензии по качеству, ассортименту, количеству, а также по возврату денежных средств за товары, работы или услуги по использованным Купонам должны быть направлены непосредственно Исполнителю по конкретному Предложению. Ответственность за отказ Исполнителя от исполнения обязательств по предоставлению товаров, работ или услуг возлагается непосредственно на Исполнителя.

4.4. Возврат денежных средств по использованным Купонам Общество не производит.

4.4. После предоставления Исполнителем Клиенту соответствующего товара, работы или услуги, Клиент обязан по требованию Исполнителя или Общества подписать все необходимые первичные документы, сообщить Пин-код (при наличии такого требования в Предложении) либо передать Купон Исполнителю.

4.4. В случае, если Исполнитель письменно обратился в Общество с жалобой об отказе Клиента предоставить Пин-код Купона, Общество отставляет за собой право обратиться к Клиенту посредством электронной почты с запросом о качестве и факте предоставления товара, работы или услуги. Если в течение 15 дней с момента направления электронного письма Клиент не предоставил Пин–код или не направил мотивированный отказ о его передачи Обществу или Исполнителю с предоставлением доказательств, обосновывающих правомерность такого отказа Клиента, то Общество вправе принять решение о признании в одностороннем порядке такого Купона использованным.

4.4. Несоответствие предъявляемого Клиентом Купона форме Купона, установленной Обществом (в том числе нарушение любого рода систем защиты Купона) влечет его недействительность.

4.4. Документы (акты, накладные, гарантийные талоны) по приобретенным у Исполнителей товарам, работам и услугам Клиент имеет вправе требовать непосредственно у Исполнителей. Общество вправе, но не обязано содействовать Клиенту в получении таких документов у Исполнителей.

V. НАЧИСЛЕНИЕ, СПИСАНИЕ И ИСПОЛЬЗОВАНИЕ ПЛАЗМАБОНУСОВ.

5.5. За операции, предусмотренные данной Офертой, произведенные в рамках подписанных договоров с Пользователями, Общество оставляет за собой право начислять ПлазмаБонусы на Счета Клиента в Личном кабинете. 

5.5. Личный кабинет Клиента на Сайте может иметь один или несколько Счетов.

5.5. Каждое зачисление ПлазмаБонусов Клиенту осуществляется на отдельный Счет, если иное не установлено на Сайте.

5.5. ПлазмаБонусы могут быть использованы только для получения скидок на товары, работы или услуги Исполнителей по размещенным на Сайте действующим Предложениям. В случае расторжения (отзыва акцепта) настоящей оферты между Клиентом и Обществом, все начисленные и неизрасходованные ПлазмаБонусы аннулируются. 

5.5. ПлазмаБонусы не являются какой-либо формой валюты и ни при каких условиях не могут быть переведены в денежный эквивалент в наличной или безналичной форме. 

5.5. ПлазмаБонусы подтверждают право получения скидки на оплату товара, работы или услуги любого Исполнителя по размещенным на Сайте действующим Предложениям. Клиент вправе при осуществлении расчетов за товары, работы или услуги Исполнителя, использовать имеющиеся на его Счетах ПлазмаБонусы, получив скидку на оплату товара, работы или услуги Исполнителя в размере 1 (Один) Российский рубль за 1 ПлазмаБонус посредством перечисления через Сайт имеющихся у Клиента ПлазмаБонусов Исполнителю.

5.5. Максимальный размер скидки на товары, работы или услуги Исполнителя, которую Клиент может получить по ПлазмаБонусам, составляет 100 % и определяется в Предложении Исполнителем самостоятельно.

5.5. Клиент вправе самостоятельно установить в Личном кабинете ограничения по максимальному размеру скидки на товары, работы или услуги Исполнителя, которую Клиент может получить по ПлазмаБонусам. Ограничения, уставленные Клиентом, применяются в части, не противоречащей условиям Предложений Исполнителей.

5.5. Период времени, в течение которого Клиент обязуется потратить ПлазмаБонусы, начисленные Обществом за размещение услуг на Сайте «РОСОБМЕН» в соответствии с условиями «Договора купли-продажи ПлазмаБонусов» устанавливается Обществом и составляет _ 180________ календарных дней с даты получения Клиентом ПлазмаБонусов на Счет в Личном кабинете. В случае если ПлазмаБонусы не будут израсходованы Клиентом в течение срока, указанного в настоящем пункте Оферты, с момента их получения на Счет в Личном кабинете, Общество в одностороннем порядке производит списание неизрасходованных Клиентом в указанный срок ПлазмаБонусов, если иное не будет указано Обществом на Сайте.

5.5. Клиент может иметь несколько Счетов в личном кабинете.

5.5. Клиент имеет право передать ПлазмаБонусы другому Клиенту, для чего необходимо заполнить соответствующую форму на странице http://rosobmen.com/Manage Личного кабинета Клиента. 

Для проведения транзакции ПлазмаБонусов, Клиент – отправитель ПлазмаБонусов, обязан направить скан-копию заявления в простой форме на адрес электронной почты info@rosobmen.com уведомив тем самым о своих намерениях Общество. Форма заявления для удобства выложена в личном кабинете Клиента.

5.5. Возврат ПлазмаБонусов, перечисленных Пользователем Обществу, Исполнителю или другому пользователю, не допускается.

VI. ТАРИФЫ НА УСЛУГИ ОБЩЕСТВА.
1. За использование ПлазмаБонусов при расчетах с Исполнителями за товары, работы или услуги, Клиент уплачивает Обществу вознаграждение в размере 7.5 % от суммы каждой скидки, полученной Клиентом посредством ПлазмаБонусов при расчетах за товары, работы или услуги Исполнителей. Вознаграждение уплачивается в рублях, НДС нет в связи с применением Обществом упрощенной системы налогообложения, путем перечисления денежных средств на банковский счет Общества в течение 3 (Трех) рабочих дней с момента выставления Обществом счета. Счет на оплату вознаграждения Обществу выставляется Клиенту посредством его размещения в Личном кабинете на странице http://rosobmen.com/manage/accounts/. До момента оплаты данного счета товары, работы или услуги Исполнителя, расчеты за которые Клиент намерен осуществить ПлазмаБонусами, считается неоплаченными. Оплата Вознаграждения Обществу возможна так-же посредством ROBOKASSA. В этом случае, вознаграждение считается оплаченным после подтверждения банком списания средств со счета Клиента и формирования Купона на услугу в личном кабинете.

6.6. В случае отсутствия задолженности перед Обществом по «Договору купли-продажи ПлазмаБонусов», «ПлазмаБонусы» начисленные Исполнителю Системой за реализацию услуг подлежат использованию. Если Пользователь не использовал вышеозначенные ПлазмаБонусы в течение 100 дней, то начиная со 101 дня со Счетов Клиента будет ежедневно списывается комиссия в размере **0,03___** % от суммы ПлазмаБонусов, размещенных на Счетах Клиента. Комиссия исчисляется в ПлазмаБонусах и списывается Обществом автоматически. 

VII. ЗАКЛЮЧИТЕЛЬНЫЕ ПОЛОЖЕНИЯ.

7.7. Настоящая Оферта становится действительной после ее размещения на Сайте. 

7.7. Все, что не предусмотрено настоящей Офертой и Предложением Исполнителя, подлежит регулированию в соответствии с действующим законодательством Российской Федерации.

7.7. Если какое-либо из условий настоящей Оферты признано недействительным или незаконным, либо не может вступить в силу в соответствии с действующим законодательством Российской Федерации, такое положение должно быть выделено из Оферты и заменено новым положением, максимально отвечающим изначальным намерениям, содержавшимся в Оферте, при этом остальные положения Оферты не меняются и остаются в силе.

7.7. Общество вправе в любое время вносить любые изменения в текст настоящей Оферты, прекращать Оферту, размещать новую Оферту, при этом Общество обязуется в течение 5 (пяти) рабочих дней с момента изменения или прекращения настоящей Оферты, выслать всем Пользователям уведомление о таком событии по указанным при регистрации адресам электронной почты.

7.7. Новая Оферта, изменения в Оферту, прекращение Оферты становятся действительными после ее размещения на Сайте. В случае несогласия с новой редакцией Оферты Клиент имеет право отозвать Акцепт Оферты, отправив соответствующее уведомление в произвольной форме по почтовому адресу: 400087, г. Волгоград, ул. Невская, 14.

7.7. В случае возникновения противоречий, текст Оферты, размещенный на Сайте, будет иметь преимущество по сравнению с любым иным текстом Оферты.

7.7. Все споры, вытекающие из правоотношений по настоящей Оферте, разрешаются путем переговоров. В случае, если Стороны не придут к решению возникших между ними споров в ходе переговоров, такие споры должны быть переданы на решение в суд Российской Федерации с обязательным соблюдением претензионного порядка. Срок ответа на претензию составляет 1 (один) месяц.

7.7. Информация, предоставленная Обществом, не может служить основанием для предъявления Обществу требований о возмещении убытков, возникших в связи с предоставленной информацией.

VIII. АДРЕСА И РЕКВИЗИТЫ ОБЩЕСТВА.

Общество с ограниченной ответственностью «СУММА ТЕХНОЛОГИЙ»

Юридический и почтовый адрес: 400087, г. Волгоград, ул. Невская, 14

ИНН 3444210340, КПП 344401001, ОГРН 1133443033448, ОКПО 22392236

Директор Овчинников Иван Анатольевич

Тел. (8442) 499-229
