### ISSUE TITLE
ВАЖНО!! Не правильно выложен контент \\ Размещение услуги

### ISSUE THREAD

**Issue by Shtirhunov** [vfedyanov/rosobmen#207]
1) Прошу перенести контент из опции \Регистрация в системе\ в опцию  \Размещение услуги\ .

2) в опцию \Регистрация в системе\  после виде-оряда необходимо выгрузить пошаговую инструкцию по регистрации в личном кабинете:

РЕГИСТРАЦИЯ

1) Переходим во вкладку \ВХОД
2) Выбираем \  Зарегистрироваться в системе.
3) Действуем согласно пошаговой инструкции

**Comment by vfedyanov** [comment]
Перемещение выполнил.
Текст по регистрации не выглядит законченным. Выложить его в таком виде?

**Comment by Shtirhunov** [comment]
Да, выкладывай пока так.
