### ISSUE TITLE
Информация о пользователе из Админки _ Нужно видеть дату регистрации

### ISSUE THREAD

**Issue by Shtirhunov** [vfedyanov/rosobmen#208]
http://rosobmen.com/Manage/Admin#users/

для понимания актуальности пользовательского списка, из админки необходимо видеть дату регистрации пользователя.
Прошу доработать.

![2014-12-15_101827](https://cloud.githubusercontent.com/assets/9961638/5431943/c47bc9ac-8443-11e4-9eb8-0324c26a3ad7.jpg)

**Comment by vfedyanov** [comment]
Дата должна показываться под номером телефона или вместо номера, если он не указан. Чтоб заработало, нужно обновить кэш браузера.
