### ISSUE TITLE
!!!!!! При оплате услуги за деньги через Робокассу, невозможно распечатать купон.

### ISSUE THREAD

**Issue by Shtirhunov** [vfedyanov/rosobmen#215]
После оплаты услуги за деньги через Робокассу , из личного кабинета покупателя невозможно распечатать купон.
У поставщика услуги и в Админке все информируется и генерируется код...
![2015-01-22_133649](https://cloud.githubusercontent.com/assets/9961638/5854163/0b56ee54-a23c-11e4-9caa-7ae49d92261e.jpg)
![2015-01-22_133716](https://cloud.githubusercontent.com/assets/9961638/5854165/0ecb6010-a23c-11e4-8b7c-4d62bf2fc81b.jpg)

У покупателя.....

1) Не отображается информация во вкладке "КУПОНЫ"
![2015-01-22_133425](https://cloud.githubusercontent.com/assets/9961638/5854115/6db922d4-a23b-11e4-9bd8-89102796cd58.jpg)

2) Не отображается информация во вкладке "Оповещения"

![2015-01-22_133327](https://cloud.githubusercontent.com/assets/9961638/5854107/5488a1fe-a23b-11e4-8027-de330bcb3252.jpg)

**Comment by vfedyanov** [comment]
Добавлена сортировка по купонам.
Оповещения о совершении покупки на сайте не предусмотрены, поэтому информация о новых купонах в оповещениях не выводится.
