### ISSUE TITLE
Генерация счета на оплату услуги или комиссии

### ISSUE THREAD

**Issue by Shtirhunov** [vfedyanov/rosobmen#217]
Необходимо настроить генерацию счета на оплату товара (услуги) .

![default](https://cloud.githubusercontent.com/assets/9961638/5901959/8b0c8a5c-a587-11e4-85dd-f7e51f1ceb81.jpg)

**Comment by vfedyanov** [comment]
а в экселе или ворде такого счета нет?

**Comment by Shtirhunov** [comment]
есть, завтра вышлю в почту

-- 
С уважением,
 Андрей Штырхунов
+7(909) 383-80-00

26.01.2015, 22:46, "vfedyanov" notifications@github.com:

**Comment by Shtirhunov** [comment]
типовой счет можно взять в интернете, форм полно в сети
