### ISSUE TITLE
class=container в личном кабинете

### ISSUE THREAD

**Issue by StepanOvchinnikov** [vfedyanov/rosobmen#26]
http://shot.qip.ru/00dQu8-519gZJGVyA/

**Comment by Igorbek** [comment]
я его намеренно убрал, ибо очень узко.
могу вернуть, не проблема.

**Comment by Igorbek** [comment]
решите, растянутый оставлять или поставить в фиксированный контейнер.

**Comment by StepanOvchinnikov** [comment]
давай так
давай скрин в эту задачу и верни фиксированный. сравним
я за фикс

у меня так http://shot.qip.ru/00dQu8-519gZJGVRu/

**Comment by Igorbek** [comment]
Ну раз за фикс, будет фикс.
