### ISSUE TITLE
Регистрация: английский + неадекватные требования к паролю с плохими поясненеиями

### ISSUE THREAD

**Issue by vfedyanov** [vfedyanov/rosobmen#3]
требует длину, разные регистры, спецсимвол и цифру. надо бы упростить.

**Comment by Igorbek** [comment]
Пиши требования к паролю.

**Comment by StepanOvchinnikov** [comment]
не менее 6 символов. никаких требований к символам

**Comment by antonkarpov33** [comment]
Не получилось зарегистрироваться
