### ISSUE TITLE
Остается видна верхняя часть первой страницы

### ISSUE THREAD

**Issue by antonkarpov33** [vfedyanov/rosobmen#35]
кнопки "как это работает" и "наверх" должны быть после прокрутки одного вида и на одном месте

http://shot.qip.ru/00rdAU-5b4CffOw5/

**Comment by Igorbek** [comment]
Это к верстке. @StepanOvchinnikov ставлю на тебя.

**Comment by StepanOvchinnikov** [comment]
Малой кровью задача не решается. 

Первый экран автоматически подтягивается под реальный размер монитора человека.
Второй - определяется высотой контента. Будет больше написано -- займет больше места. Меньше -- останется больший хвост.

Если переделать на жесткую подгонку -- на некоторых экранах (например, маленьких) может перестать помещаться контент.
