### ISSUE TITLE
надписи об услугах на главной и ссылки на них

### ISSUE THREAD

**Issue by StepanOvchinnikov** [vfedyanov/rosobmen#37]
http://shot.qip.ru/00dQu8-619gZJGVRB/

**Comment by Igorbek** [comment]
Да мне тоже странно, но какие предложения? Их нет еще.
Пока сделал поиском, так с @vfedyanov согласовали.

**Comment by StepanOvchinnikov** [comment]
думаю надо заменить поиск на прямые ссылки. или пусть теги летают, то есть чтобы клик на надпись приводил к показу чего-то адекватного

**Comment by vfedyanov** [comment]
в доп ТЗ
