### ISSUE TITLE
мертвый подвал. все неактуально

### ISSUE THREAD

**Issue by StepanOvchinnikov** [vfedyanov/rosobmen#39]
Дата -- 13 год. надо 14. перед "г" пробел, после -- точка. а лучше -- редактируемо
ссылки на соцсети неверные. желательно чтобы настраивались
ссылка на ИВ отсутствует. надо на http://www.intervolga.ru

http://shot.qip.ru/00dQu8-519gZJGVRD/

**Comment by Igorbek** [comment]
Давайте все ссылки, которые нужны. У меня их нет.
Редактируемо не будет.

**Comment by StepanOvchinnikov** [comment]
ссылка на ИВ http://www.intervolga.ru/
ссылки на соцсети нужно чтобы редактировались, пусть путем правки файла. пусть Федянов знает где редактируется
в данный момент эти ссылки никому не известны
