### ISSUE TITLE
Сохранение профиля

### ISSUE THREAD

**Issue by vfedyanov** [vfedyanov/rosobmen#4]
http://shot.qip.ru/00etiM-5UvvpmcCv/

**Comment by Igorbek** [comment]
посмотрим.

**Comment by Igorbek** [comment]
Не воспроизводится. У меня сохранилось нормально. Получил код.
@vfedyanov попробуй еще раз, переоткрой если повтроряется.

**Comment by Igorbek** [comment]
Причина - неправильно введен номер телефона.
Исправить уже нельзя... надо подумать как исправить, чтобы можно новый номер ввести.
Переоткрываю.
