### ISSUE TITLE
неправильно работает "назад" после поиска с главной

### ISSUE THREAD

**Issue by StepanOvchinnikov** [vfedyanov/rosobmen#42]
поиск на главной путем клика по тегу
потом "назад"
и оказывается на такой больной странице

http://shot.qip.ru/00dQu8-619gZJGVRG/

**Comment by Igorbek** [comment]
Эта картинка не сразу подгружается, но работает.
Там баг, что она в какой-то момент вообще не загружается исправлен.
У меня не воспроизводится.
Посмотри, точно она вообще не появляется? Спустя некоторое время.

**Comment by StepanOvchinnikov** [comment]
исправлено, все ок
