### ISSUE TITLE
некоторые ссылки в основном меню никуда не ведут

### ISSUE THREAD

**Issue by StepanOvchinnikov** [vfedyanov/rosobmen#45]
http://shot.qip.ru/00dQu8-519gZJGVRJ/

**Comment by Igorbek** [comment]
Мне как бы тексты этих страниц нужны.
Сделаю временные.

**Comment by vfedyanov** [comment]
Степан?

**Comment by StepanOvchinnikov** [comment]
страницы нужно сделать, а тексты для них мы будем менять неоднократно
нужно показать Федянову (если нельзя сделать цивильный редактор) где это физически хранится
