### ISSUE TITLE
шрединбаг. при вводе адреса и попадании на сайт периодически вижу две шапки и никакой картинки вверху

### ISSUE THREAD

**Issue by StepanOvchinnikov** [vfedyanov/rosobmen#47]
http://shot.qip.ru/00dQu8-619gZJGW0y/

**Comment by Igorbek** [comment]
можешь в таком случае открыть web консоль и посмотреть - есть ли там ошибки?
У меня не воспроизводится.

**Comment by StepanOvchinnikov** [comment]
http://shot.qip.ru/00dQu8-519gZJGWGR/ есть ошибка загрузки шрифта

что касается причины упомянутого бага -- имхо дело в очень медленной отдаче исходной картинки и соседних.
Кажется, Алексей Шкарупа про это писал.

эта картинка отдается 0.3 секунды http://shot.qip.ru/00dQu8-619gZJGWGW/, а эта 1.3 (хотя она крохотная) https://www.evernote.com/shard/s303/sh/cb255a57-9516-4033-be67-1d4876964b47/7d0d7e80faf9c4a6fa1a9323a6eb8317

**Comment by Igorbek** [comment]
Этот баг, с 2-мя картинками, пофиксен. Загрузка шрифта действительно не идет, но это дубль #85
