### ISSUE TITLE
после редактирования услуг админом не сразу выводится новый статус

### ISSUE THREAD

**Issue by StepanOvchinnikov** [vfedyanov/rosobmen#51]
http://shot.qip.ru/00dQu8-519gZJGW0C/

**Comment by Igorbek** [comment]
да кеш. все некотрые отдельные страницы не синхронизируются при действиях.

**Comment by vfedyanov** [comment]
Игорь, мне на понятен статус этого тикета. Переведи ламеру что сделано или почему это сделано не будет

**Comment by Igorbek** [comment]
Сейчас это не должно воспроизводиться. Проверьте.

**Comment by StepanOvchinnikov** [comment]
проверено, закрыто
