### ISSUE TITLE
после одобрения и публикации услуги, равно как и при отправке на доработке, отправляется ли уведомление на почту?

### ISSUE THREAD

**Issue by StepanOvchinnikov** [vfedyanov/rosobmen#53]
после одобрения и публикации услуги, равно как и при отправке на доработке, отправляется ли уведомление на почту?

я не увидел

**Comment by Igorbek** [comment]
не отправляется. есть в ТЗ? не нашел.

**Comment by vfedyanov** [comment]
в доп ТЗ
