### ISSUE TITLE
злобный баг. после снятия услуги с публикации ПБ не снимаются.

### ISSUE THREAD

**Issue by StepanOvchinnikov** [vfedyanov/rosobmen#57]
http://shot.qip.ru/00dQu8-619gZJGW0H/

повторная публикация кстати не приводит к повторному начислению, что правильно

**Comment by Igorbek** [comment]
По ТЗ снимать, если уже что-то куплено, нельзя.
И вообще, предполагается, что ты договор займа оформляешь.
Покажите где в ТЗ процедура на данный случай, не нашел.

**Comment by vfedyanov** [comment]
Так, Игорь, что будет если уменьшить число услуг? Услуга не переопубликуется? Потребует повторной модерации?
В принципе можно просто запретить что-либо менять после модерации.

Напиши, плиз реализованную логику.

Мне кажется, тикет можно закрыть, но хочу уточнить.

**Comment by Igorbek** [comment]
менять нельзя, но администратору можно. никакие финансы в этой связи не изменятся.
