### ISSUE TITLE
хлебные крошки на странице услуги

### ISSUE THREAD

**Issue by StepanOvchinnikov** [vfedyanov/rosobmen#59]
http://shot.qip.ru/00dQu8-619gZJGW0J/

кстати уровень "Каталог" можно переименовать во "все". место сэкономим и смысла больше

**Comment by Igorbek** [comment]
Как и на сколько подрезать? А если много вложенных? Верстка должна здесь хорошо отрабатывать.

**Comment by vfedyanov** [comment]
Степан?

**Comment by StepanOvchinnikov** [comment]
версткой сделать не получается
общая длина помещающихся в хлебные крошки букв с пробелами -- 40.
нужно взять 19 сначала, 18 с конца, и поставить между ними ...

19 и 18 условно, можно 29 и 8

при этом Каталог надо переименовать во Все

**Comment by Igorbek** [comment]
а когда уровней вложенности больше? точно не сможете верстку улучшить? чтоб многострочно работало нормально?

**Comment by StepanOvchinnikov** [comment]
инфу принял. поговорю с Артемом и Алексеем, дадим ответ

**Comment by shkarupa-alex** [comment]
При таком дизайне хлебных крошек точно не сможем.
Если убрать у хлебных крошек оформление и (ромбики в конце, бордюр) и оставить обычные ссылки - проблема будет исчерпана. А при текущем дизайне сделать красивое переползание на 2ю строку не получится.

**Comment by StepanOvchinnikov** [comment]
Леша, прошу сделать (можно силами Андрея Гладкова) новую верстку крошек
этот дизайн не стоит такого геморроя с подрезанием.

срок -- до конца недели

**Comment by Igorbek** [comment]
Если еще не доделали, почему на меня поставили?

**Comment by shkarupa-alex** [comment]
Стили хлебных крошек мы поправили и приложили в другом тикете - тоже про крошки

**Comment by Igorbek** [comment]
откатил (Igorbek/plazma#161), жду #177
