### ISSUE TITLE
Регистрация. Капча, язык, восстановление пароля

### ISSUE THREAD

**Issue by StepanOvchinnikov** [vfedyanov/rosobmen#6]
1. Нет капчи
2. Перевести все на русский, в том числе сообщения о валидации полей
   The Email field is not a valid e-mail address.
   The password and confirmation password do not match.
3. есть ли функциональность "я забыл пароль?"
   она 100% потребуется, является стандартной
4. После открытия ссылки сообщение опять на англ, да еще и со слипшимся заголовком CONFIRMACCOUNT
   http://shot.qip.ru/00dQu8-619gZJGVyj/

**Comment by Igorbek** [comment]
1,2 готово, 3,4 - tbd
