### ISSUE TITLE
страница покупки услуги пугающе недружественна

### ISSUE THREAD

**Issue by StepanOvchinnikov** [vfedyanov/rosobmen#62]
http://shot.qip.ru/00dQu8-619gZJGW0N/

слово Параметры -- плохое. надо написать "покупка услуги "СВИНЫЕ ПОЛУТУШИ ОПТОМ" "

выбор варианта оплаты - не в строку, а отдельным блоком по 1 в строке

максимально доступноЕ количество -- орфография

под заголовком надо поле для вводного текста. без высшего образования фиг кто что поймет

готов подумать и нарисовать годную сетку

**Comment by Igorbek** [comment]
Думай, рисуй :+1:

**Comment by vfedyanov** [comment]
Закрываю, отправляем в доп ТЗ
