### ISSUE TITLE
Время на сервере -- североамериканское среднее?

### ISSUE THREAD

**Issue by StepanOvchinnikov** [vfedyanov/rosobmen#63]
http://shot.qip.ru/00dQu8-519gZJGW0O/

у меня 8:39

**Comment by Igorbek** [comment]
Хм... странно. На сервере везде только UTC, а на клиенте должно твое ставится.... через momentjs работает на клиенте. Посмотрим.

**Comment by Igorbek** [comment]
Не могу найти, чтобы воспроизводилось. Я менял обработку дат на клиенте, возможно это пофиксило. Если повторится, переоткрывайте.
