### ISSUE TITLE
модератор редактирует количество услуг, на состоянии счета это не отражается

### ISSUE THREAD

**Issue by StepanOvchinnikov** [vfedyanov/rosobmen#67]
http://shot.qip.ru/00dQu8-519gZJGW0T/

http://shot.qip.ru/00dQu8-619gZJGW0U/

**Comment by Igorbek** [comment]
Нужны четкие процедуры на этот счет. Вопрос скользкий.

**Comment by StepanOvchinnikov** [comment]
мои предложения:
1 (лучше). корректно обрабатывать. считать разницу до-после и записывать такое "модераторское" списание или пополнение как отдельную запись в журнале движения средств
2 (хуже). запретить модератору такие действия.
3 (совсем плохо). заставить модератору вручную корректировать счет

**Comment by StepanOvchinnikov** [comment]
нужна помощь-поддержка @vfedyanov

**Comment by vfedyanov** [comment]
Мы это уже обсуждали? Если это не дубль другого тикета, то считаю

 что в настоящее время необходимо оставить как есть. Модератор может все. Он может творить произвол. Менять баланс в системе.
в нормальной ситуации, так быть не должно и модератор вручную потом должен будет поменять все параметры счета.

почему стоит это отложить:
мы не знаем кейсов. мы не знаем что, когда и при каких обстоятельствах будет происходить.

**Comment by vfedyanov** [comment]
Степан, прочти, я закрываю.

**Comment by StepanOvchinnikov** [comment]
я против идеологически. мы при таком состоянии вопроса тупо не сможем отвечать на вопросы партнеров "куда делось то-то и то-то в системе"
как минимум система подробных логов нам нужна, чтобы было по чему разбираться

**Comment by vfedyanov** [comment]
Логи. Про логи у нас есть в ТЗ. Игорь, как их можно посмотреть? Логируется ли это?

**Comment by vfedyanov** [comment]
Игорь, есть такой пункт 9.2.7
Давай его считать за эту штуку. Норм?

**Comment by Igorbek** [comment]
Лог вынесен в задачу Igorbek/plazma#170.
