### ISSUE TITLE
Редактирование языковых файлов и почтовых шаблонов: прошу доступ

### ISSUE THREAD

**Issue by StepanOvchinnikov** [vfedyanov/rosobmen#7]
Текст на странице после регистрации и в почте корявый
http://shot.qip.ru/00dQu8-619gZJGVyh/
http://shot.qip.ru/00dQu8-519gZJGVyi/
Не будем мучить программиста его неоднократной правкой, прошу предоставить доступ к редактированию почтовых шаблонов и файлов языковых констант.

Насколько я понимаю, в MS все это есть.

**Comment by Igorbek** [comment]
Не знаю как тебе это поможет, но дал доступ к основному репозиторию.

**Comment by Igorbek** [comment]
Доступ есть, закрываю.
