### ISSUE TITLE
оплата менее 1 рубля через робокассу не прошла. в смске ошибка

### ISSUE THREAD

**Issue by StepanOvchinnikov** [vfedyanov/rosobmen#71]
http://shot.qip.ru/00dQu8-619gZJGW10/
![img_0411](https://cloud.githubusercontent.com/assets/8252959/3901436/aa551b66-22a8-11e4-94b5-5030cc03cb9d.jpg)

**Comment by Igorbek** [comment]
Ну значит не прошла. Что делать? Можешь заплатить другим способом.
Способ оплаты я не контролирую и ограничения специфичные не ввожу.
