### ISSUE TITLE
страница счетов неинформативна

### ISSUE THREAD

**Issue by StepanOvchinnikov** [vfedyanov/rosobmen#78]
http://shot.qip.ru/00dQu8-519gZJGW17/

нужно писать какая услуга и куда конкретно ушел резерв. или хотя бы ссылку давать нормальную

другие экраны столь же неинформативны http://shot.qip.ru/00dQu8-519gZJGW18/
http://shot.qip.ru/00dQu8-519gZJGW19/

**Comment by Igorbek** [comment]
Создана Igorbek/plazma#150
