### ISSUE TITLE
не открывается диалог печати купона

### ISSUE THREAD

**Issue by StepanOvchinnikov** [vfedyanov/rosobmen#80]
http://shot.qip.ru/00dQu8-619gZJGW1b/
И нужна кнопка "печать", с дейсnвием аналогичным ctrl+p

**Comment by Igorbek** [comment]
Мне бы для начала дизайн купона. Верстку его пришлите.

**Comment by vfedyanov** [comment]
Степан?

**Comment by StepanOvchinnikov** [comment]
у нас есть утвержденный дизайн купона? где?

**Comment by Igorbek** [comment]
#86 почти тоже самое - нужна верстка. будет и печать там.

**Comment by StepanOvchinnikov** [comment]
отдал купон в верстку. ждем

**Comment by StepanOvchinnikov** [comment]
верстка

https://cpiv.bitrix24.ru/workgroups/group/215/tasks/task/view/11485/

**Comment by vfedyanov** [comment]
цитата, с чего начался тикет: "http://shot.qip.ru/00dQu8-619gZJGW1b/
И нужна кнопка "печать", с дейсnвием аналогичным ctrl+p"

Это обсуждено, акцепт?
