### ISSUE TITLE
после удаления клиентом услуги начисленные за нее ПБ остаются

### ISSUE THREAD

**Issue by StepanOvchinnikov** [vfedyanov/rosobmen#81]
http://shot.qip.ru/00dQu8-619gZJGW1d/

**Comment by Igorbek** [comment]
Да, и долг остался ))
Ну вы пропишите workflow на этот счет.

**Comment by StepanOvchinnikov** [comment]
workflow: система обработчиков событий редактирования, удаления платежей, услуг, клиентов, при которой:
- иногда операция запрещается 
- всегда если операция разрешена, это корректно отражается в учете

я бы еще написал некий отчет (Федянов называет это "аудитом") на предмет общей арифметической целостности системы, что нигде ничего из воздуха не берется

и контролировал бы глазами и кодом. если копится ошибка -- есть что исправлять.
что-то вроде того что общая сумма денег в системе должна быть равна стоимости внесенных услуг за минусом демереджа и комиссий системы

требуется помощь @vfedyanov

**Comment by vfedyanov** [comment]
Я не понимаю этих "лимитов".
Мы с Игорем много раз говорили, что лимитов в релизе не будет.

Арифметическая целостность очевидна и неоднократно обсуждена.
У каждого пользователя есть: актив и пассив. То есть Доступных ПБ для трат и его Долг перед системой.
Если он покупает за ПБ -- актив уменьшается.
Если у него покупают -- его долг уменьшается.

Только сделки (передачи ПБ) меняют состояние счета автоматически.
Все остальное меняет администратор.

В нашем случае беды нет. актив и пассив остаются на местах. Он должен столько же, сколько и может. Но теперь он должен только денег, а не услуг. Сам виноват.

**Comment by Igorbek** [comment]
изменю отображение "лимитов" на "актив". Будет как надо. Ща сделаю.
Актив = Счет - Лимит (лимит отрицательный)
Пассив = -Лимит
при покупках, увеличивается счет и увеличивается лимит (до 0).

**Comment by vfedyanov** [comment]
фенкс

**Comment by vfedyanov** [comment]
Степан, ты открывал тикет. Согласен/несогласен. Закрываем?

**Comment by StepanOvchinnikov** [comment]
я не все понял в вашей переписке, если честно. против описанного способа не возражаю

суть глюка в том что нехитрая админская манипуляция приводит к дыре в финансах

глюк исправлен? можно проверить?

**Comment by vfedyanov** [comment]
глюка не было, потому он не исправлен :) Попробуй понять. А то не приятно быть единственным, кто принимает эти решения ;)

**Comment by vfedyanov** [comment]
Закрыто, раз нет комментариев от Степана

**Comment by StepanOvchinnikov** [comment]
еще раз. я удаляю услугу в админке. имею право? 

при этом мой баланс (и право пользования услугами) не меняется. это нормально?
если да, объясните почему

начальный баланс http://shot.qip.ru/00dQu8-619gZJGXoB/
были услуги http://shot.qip.ru/00dQu8-619gZJGXoC/
все поснимал http://shot.qip.ru/00dQu8-619gZJGXoD/
баланс по окончании http://shot.qip.ru/00dQu8-619gZJGXoE/

**Comment by Igorbek** [comment]
там же вроде как долговая расписка остается. @vfedyanov утверждал, что если подпишешь кабалу - то все :-)

**Comment by vfedyanov** [comment]
Услугу просто так удалить нельзя. Ты снимал услуги как админ или как простой пользователь?
Если как админ -- все верно.
Если как пользователь -- нет.

Цитирую себя выше
"Арифметическая целостность очевидна и неоднократно обсуждена.
У каждого пользователя есть: актив и пассив. То есть Доступных ПБ для трат и его Долг перед системой.
Если он покупает за ПБ -- актив уменьшается.
Если у него покупают -- его долг уменьшается.

Только сделки (передачи ПБ) меняют состояние счета автоматически.
Все остальное меняет администратор.

В нашем случае беды нет. актив и пассив остаются на местах. Он должен столько же, сколько и может. Но теперь он должен только денег, а не услуг. Сам виноват."
