### ISSUE TITLE
Большая картинка на главной странице грузится 23 секунды на оч быстром интернете

### ISSUE THREAD

**Issue by shkarupa-alex** [vfedyanov/rosobmen#84]
Наиболее вероятно что она отдается из ASP.
Ее бы или на CDN выгрузить или nginx перед ASP воткнуть

Ну и саму картинку если пересохранить со сжатием 85-90 процентов визуального качества скорее всего не потеряем, а размер уменьшится с 1.7Мб до 700Кб

**Comment by Igorbek** [comment]
Она отдается не из ASP. Она просто отдается как файл.
Не очень понимаю что там ее так тормозит. У меня тут она грузится быстро ))
Если что-то сделаете, то гуд.

**Comment by vfedyanov** [comment]
Степан?

**Comment by StepanOvchinnikov** [comment]
если Игорь прав что отдается просто веб-сервером просто как файл, то либо:
- тупит веб-сервер с отдачей такого файла. его конфигурирование технически сложно и требует постоянного воспроизведения проблемы. я считаю это зоной ответственности разработчика системы, но понимаю что отладка может оказаться крайне трудоемкой
- тупят линии связи между РФ и североамериканским континентом, где физически находится AZURE. это может быть решено прикручиванием CDN-системы, но это далеко за пределами текущих планов и приоритетов

проблема признана нерешаемой на текущий момент и не столь приоритетной

ps если проблема будет повторяться, стоит попробовать сжать ее до худшего качества или, например, положить на сервер в россии. типа intervolga.ru/rosobmen.jpg
это некрасивые, но быстрые решения
