### ISSUE TITLE
Mac + chrome = не грузится FontAwesome

### ISSUE THREAD

**Issue by shkarupa-alex** [vfedyanov/rosobmen#85]
https://www.evernote.com/shard/s303/sh/83784b03-e33c-4dea-8e4e-71a1c315f705/256c944fa397be070f91a00812a04c80

**Comment by Igorbek** [comment]
А на верстке такое же происходит? Не проверяли? В чем различие?

**Comment by shkarupa-alex** [comment]
нужно в less (bootstrap.less который в самих стилях а не в поставке bootstrap) проверить правильность указания пути к fontawesome и наличие этого файла на сервере

**Comment by Igorbek** [comment]
Кажется нашел, при следующем деплое пофиксится.

**Comment by Igorbek** [comment]
Открываю заново, не пофиксилось.

**Comment by Igorbek** [comment]
fixed
