### ISSUE TITLE
вид купона не по ТЗ

### ISSUE THREAD

**Issue by StepanOvchinnikov** [vfedyanov/rosobmen#86]
http://shot.qip.ru/00dQu8-519gZJGW1f/

**Comment by Igorbek** [comment]
Что-то я не нашел вид купона в ТЗ (ткните =). Вы просто сделайте верстку купона - и я ее вставлю. Это не проблема.

**Comment by vfedyanov** [comment]
Купон будет

**Comment by vfedyanov** [comment]
https://drive.google.com/file/d/0B5cwvw3_6anFcjJvM1lvX2xyaWM/edit?usp=sharing_eec. Это Степану.

**Comment by StepanOvchinnikov** [comment]
отдали в верстку. ждем примерно в среду. может слегка позже

**Comment by StepanOvchinnikov** [comment]
отдал верстку в другом тикете

**Comment by vfedyanov** [comment]
раз это дубль -- закрываю
