### ISSUE TITLE
Обязательность/доступность полей

### ISSUE THREAD

**Issue by shkarupa-alex** [vfedyanov/rosobmen#87]
https://www.evernote.com/shard/s303/sh/ac4eb878-de46-4483-a28f-264a4641b257/2787d37d988b2be56683140156d1637e

Неактивные поля требуют заполнения (валидатор ругается), но они выглядят как неактивные

**Comment by Igorbek** [comment]
Как в верстке дали, так и заполнил. Исправляйте.

**Comment by StepanOvchinnikov** [comment]
озадачил Алексея в скайпе. ответ в пн-вт

**Comment by shkarupa-alex** [comment]
Нужно заменить файл less/tpl/block.less
https://www.dropbox.com/s/0ykx8u7d7ajuwqd/block.less?dl=0

Также в этом файле я добавил правило для обязательных полей. Если добавить вот такой класс на label https://www.evernote.com/shard/s303/sh/d9cc334d-7997-4974-aaa8-08503af9d8af/94c6c0d29bd5c08e70d67a9bfb5777fe - возле него появится красная звездочка обозначающая обязательность

**Comment by Igorbek** [comment]
Я честно пытался понять какой из файлов `block.less` заменить, но так и не нашел.
Проясните, и скомпильте результирующий css вместе с #102.

**Comment by Igorbek** [comment]
Класс добавлен, css подключен, но ничего не появляется.

**Comment by shkarupa-alex** [comment]
Какой класс? Может я не в курсе и что-то передавалось в обход меня...
Если нет возможности компилировать из less то сложно сказать что именно и где нужно заменить. Но я попробую.

Вот css http://rosobmen.com/Content/css?v=nCZRf9tDzrKlQhylFweKRULiVdBqDNKP8zxju0pOe7k1

В нем есть строка:
textarea.form-control{background:#ece8de;border-radius:0;border-color:#cbc3b6;color:#a0835e}

Ее нужно заменить на строку:
textarea.form-control{border-radius:0;border: 1px solid #fea636;}

**Comment by StepanOvchinnikov** [comment]
Леша, класс выше написан тобой на скриншоте
label class="required"

лесс Игорь  смог скомпилировать

**Comment by shkarupa-alex** [comment]
Ага, вот как.
Строчки что я привел выше призваны сделать фон textarea белым и обводку оранжевой.

А чтобы required заработал добавьте в css вот это
form .required:after {
    content: '*';
    color: red;
    font-weight:bold;
}

**Comment by Igorbek** [comment]
> Нужно заменить файл less/tpl/block.less
> https://www.dropbox.com/s/0ykx8u7d7ajuwqd/block.less?dl=0
> 
> Также в этом файле я добавил правило для обязательных полей

вот я этот файл уже обновлял.

**Comment by StepanOvchinnikov** [comment]
Игорь, дай пожалуйста ссылку, скриншот и кусок дом-дерева, который работает не как нужно. Изучим вопрос

**Comment by Igorbek** [comment]
Ну что ж вы? Там же все есть (лишнее порезал):

``` html
<div class="form-group">
    <label data-bind="..." class="required">Фамилия</label>
    <input type="text" data-bind="..."><span class="text-danger" style="display: none;"></span>
</div>
```

вот
![image](https://cloud.githubusercontent.com/assets/1929486/4565076/cf401372-4f1c-11e4-904d-963c12bc9303.png)

текущий css и less есть в исходниках. @StepanOvchinnikov у тебя есть доступ. Лежит здесь: https://github.com/Igorbek/plazma/tree/develop/v1/src/Plazma/Plazma.Web/Content

**Comment by shkarupa-alex** [comment]
Игорь, добавь вот это правило хоть в css хоть в less (оно валидно и там и там)

form .required:after {
content: '*';
color: red;
font-weight:bold;
}

**Comment by shkarupa-alex** [comment]
Добавить можно в какое угодно место, лишь бы оно появилось в css

**Comment by Igorbek** [comment]
ok...
