### ISSUE TITLE
Пустая страница (даже заголовка нет)

### ISSUE THREAD

**Issue by shkarupa-alex** [vfedyanov/rosobmen#88]
http://rosobmen.com/Manage#products

**Comment by Igorbek** [comment]
Хм... у меня не пустая. Можете дать что в консоли?

**Comment by Igorbek** [comment]
@shkarupa-alex пинг

**Comment by shkarupa-alex** [comment]
В консоли было пусто.
Через некоторое время страница стала открываться, но оч тяжко
Причем если память не изменяет открываться стало когда я заполнил профиль. А изначально попытался открыть эту страницу сразу после регистрации

**Comment by Igorbek** [comment]
Попробовал воспроизвести - не получается. Если будет повторяться, переоткроем.

**Comment by shkarupa-alex** [comment]
> > Хм... у меня не пустая. Можете дать что в консоли?
> > Проблема наблюдалась минут 5 сразу после регистрации потом пропала
