### ISSUE TITLE
Дайте мне кнопку!

### ISSUE THREAD

**Issue by olga7** [vfedyanov/rosobmen#89]
У меня проблему начались сразу. Мне предложили начать с поиска. Поиск по слову "отдых" мне выдал следующую страницу http://shot.qip.ru/00mxnL-59mYYBh4P/
Где:
результатов поиска нет
Выбор категории в выпадающем списке никаких результатов не дает
ссылки на каталог перед глазами нет
Единственное слово "Каталог" в хлебных крошках некликабельно.

Дайте мне кнопку!

Почему все так технически, мне понятно. Но что мне-Пользователю делать дальше - непонятно.

**Comment by Igorbek** [comment]
Скажите что делать в таком случае.
Дайте большую кнопку, которую поставить в центре ))
Ставлю на @StepanOvchinnikov

**Comment by StepanOvchinnikov** [comment]
http://shot.qip.ru/00dQu8-619gZJGWl6/ думаю так и все

**Comment by vfedyanov** [comment]
Игорь, норм?

**Comment by vfedyanov** [comment]
обсуждали. Акцепт?
