### ISSUE TITLE
где каталог?

### ISSUE THREAD

**Issue by olga7** [vfedyanov/rosobmen#91]
Я еще незнакома с сервисом, у меня в голове нет готово поискового запроса (у меня еще не сформировалась потребность). 
Мне нужно познакомиться с имеющимися предложениями.... 
Мне кажется в раскрывающемся меню должны быть категории каталога, а не все что угодно, где каталог неприметно стоит самым последним пунктом.

**Comment by Igorbek** [comment]
Полностью согласен.
