### ISSUE TITLE
крошки на детальной

### ISSUE THREAD

**Issue by olga7** [vfedyanov/rosobmen#93]
вообще некрасиво (обрывается верхняя строка) http://shot.qip.ru/00mxnL-69mYYBh4Z/

**Comment by Igorbek** [comment]
Дайте получше верстку.

**Comment by StepanOvchinnikov** [comment]
этот вопрос мы обсуждали в другом тикете, номер не скажу
решение: программно укоротить строку чтобы не переносились крошки.
тут то же самое

**Comment by StepanOvchinnikov** [comment]
попробуем дать другую верстку, но не гарантирую

**Comment by shkarupa-alex** [comment]
Замените файлом https://www.dropbox.com/s/e06b2ahmbnarir9/block.less?dl=0
аналогичный по пути less/breadcrumb/

**Comment by shkarupa-alex** [comment]
собственно обсуждаем ту же проблему что и https://github.com/Igorbek/rosobmen/issues/59

**Comment by Igorbek** [comment]
откатил (Igorbek/plazma#161), жду #177

**Comment by Igorbek** [comment]
Я так понимаю закрыто в #177
