### ISSUE TITLE
Не получается купить услугу

### ISSUE THREAD

**Issue by shkarupa-alex** [vfedyanov/rosobmen#95]
https://www.evernote.com/shard/s303/sh/74889b94-3dca-4ae8-9050-c394dc6b6860/1f97bb364de23fa8c0c77cc5dcf89af9

При этом в поле "счет" нет ничего (в смысле выбрать нечего)

**Comment by Igorbek** [comment]
а есть счет или его нет?

**Comment by shkarupa-alex** [comment]
Я зарегистрировался, заполнил профиль (там где адреса, кор/бик) и попытался купить

**Comment by Igorbek** [comment]
Если нет счета продукта, то и купить на счет продукта нельзя.
Тоьлко за рубли.
