### ISSUE TITLE
услуги не выбираются

### ISSUE THREAD

**Issue by olga7** [vfedyanov/rosobmen#96]
Три пункта в выпадающем списке (услуги в середине списка) не могут быть выбраны http://shot.qip.ru/00mxnL-69mYYBh59/ 

А если снять все выбранные категории, то в строке остается "Услуги, услуги, услуги,услуги..."
http://shot.qip.ru/00mxnL-69mYYBh5e/

**Comment by Igorbek** [comment]
Хм... посмотрим, разберемся. Бага, определенно.

**Comment by Igorbek** [comment]
Похоже дубль #99, проверю фиксит ли.

**Comment by Igorbek** [comment]
Работает.
