### ISSUE TITLE
21 одно замечание от Алисы. Игорь, пройдись. Большая часть выглядит как баги. Все трудоемкие не баги просто пометь по номерам

### ISSUE THREAD

**Issue by Alisa23** [vfedyanov/rosobmen#97]
15 в админке почему пусто, вроде счета есть уже
![15](https://cloud.githubusercontent.com/assets/8436576/3903260/c72eaee8-22c9-11e4-8397-957b908e1750.png)

22 что то с фоткой при детальном просмотре
![22](https://cloud.githubusercontent.com/assets/8436576/3903268/c77cd1c2-22c9-11e4-81fd-1a72b2784180.png)

**Comment by vfedyanov** [comment]
В основном по делу. Выглядит как ошибки

**Comment by vfedyanov** [comment]
Все раскидал по другим задачам. Алисе спасибо, закрываю
